// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.skia.org/infra/go/paramtools"
	"go.skia.org/infra/go/query"
	"go.skia.org/infra/perf/go/dataframe"
	"go.skia.org/infra/perf/go/progress"
)

// NewDataFrameBuilder creates a new instance of DataFrameBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataFrameBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataFrameBuilder {
	mock := &DataFrameBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DataFrameBuilder is an autogenerated mock type for the DataFrameBuilder type
type DataFrameBuilder struct {
	mock.Mock
}

type DataFrameBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *DataFrameBuilder) EXPECT() *DataFrameBuilder_Expecter {
	return &DataFrameBuilder_Expecter{mock: &_m.Mock}
}

// NewFromKeysAndRange provides a mock function for the type DataFrameBuilder
func (_mock *DataFrameBuilder) NewFromKeysAndRange(ctx context.Context, keys []string, begin time.Time, end time.Time, downsample bool, progress1 progress.Progress) (*dataframe.DataFrame, error) {
	ret := _mock.Called(ctx, keys, begin, end, downsample, progress1)

	if len(ret) == 0 {
		panic("no return value specified for NewFromKeysAndRange")
	}

	var r0 *dataframe.DataFrame
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time, bool, progress.Progress) (*dataframe.DataFrame, error)); ok {
		return returnFunc(ctx, keys, begin, end, downsample, progress1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time, bool, progress.Progress) *dataframe.DataFrame); ok {
		r0 = returnFunc(ctx, keys, begin, end, downsample, progress1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dataframe.DataFrame)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, time.Time, time.Time, bool, progress.Progress) error); ok {
		r1 = returnFunc(ctx, keys, begin, end, downsample, progress1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataFrameBuilder_NewFromKeysAndRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewFromKeysAndRange'
type DataFrameBuilder_NewFromKeysAndRange_Call struct {
	*mock.Call
}

// NewFromKeysAndRange is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
//   - begin time.Time
//   - end time.Time
//   - downsample bool
//   - progress1 progress.Progress
func (_e *DataFrameBuilder_Expecter) NewFromKeysAndRange(ctx interface{}, keys interface{}, begin interface{}, end interface{}, downsample interface{}, progress1 interface{}) *DataFrameBuilder_NewFromKeysAndRange_Call {
	return &DataFrameBuilder_NewFromKeysAndRange_Call{Call: _e.mock.On("NewFromKeysAndRange", ctx, keys, begin, end, downsample, progress1)}
}

func (_c *DataFrameBuilder_NewFromKeysAndRange_Call) Run(run func(ctx context.Context, keys []string, begin time.Time, end time.Time, downsample bool, progress1 progress.Progress)) *DataFrameBuilder_NewFromKeysAndRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 progress.Progress
		if args[5] != nil {
			arg5 = args[5].(progress.Progress)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *DataFrameBuilder_NewFromKeysAndRange_Call) Return(dataFrame *dataframe.DataFrame, err error) *DataFrameBuilder_NewFromKeysAndRange_Call {
	_c.Call.Return(dataFrame, err)
	return _c
}

func (_c *DataFrameBuilder_NewFromKeysAndRange_Call) RunAndReturn(run func(ctx context.Context, keys []string, begin time.Time, end time.Time, downsample bool, progress1 progress.Progress) (*dataframe.DataFrame, error)) *DataFrameBuilder_NewFromKeysAndRange_Call {
	_c.Call.Return(run)
	return _c
}

// NewFromQueryAndRange provides a mock function for the type DataFrameBuilder
func (_mock *DataFrameBuilder) NewFromQueryAndRange(ctx context.Context, begin time.Time, end time.Time, q *query.Query, downsample bool, progress1 progress.Progress) (*dataframe.DataFrame, error) {
	ret := _mock.Called(ctx, begin, end, q, downsample, progress1)

	if len(ret) == 0 {
		panic("no return value specified for NewFromQueryAndRange")
	}

	var r0 *dataframe.DataFrame
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *query.Query, bool, progress.Progress) (*dataframe.DataFrame, error)); ok {
		return returnFunc(ctx, begin, end, q, downsample, progress1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *query.Query, bool, progress.Progress) *dataframe.DataFrame); ok {
		r0 = returnFunc(ctx, begin, end, q, downsample, progress1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dataframe.DataFrame)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, *query.Query, bool, progress.Progress) error); ok {
		r1 = returnFunc(ctx, begin, end, q, downsample, progress1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataFrameBuilder_NewFromQueryAndRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewFromQueryAndRange'
type DataFrameBuilder_NewFromQueryAndRange_Call struct {
	*mock.Call
}

// NewFromQueryAndRange is a helper method to define mock.On call
//   - ctx context.Context
//   - begin time.Time
//   - end time.Time
//   - q *query.Query
//   - downsample bool
//   - progress1 progress.Progress
func (_e *DataFrameBuilder_Expecter) NewFromQueryAndRange(ctx interface{}, begin interface{}, end interface{}, q interface{}, downsample interface{}, progress1 interface{}) *DataFrameBuilder_NewFromQueryAndRange_Call {
	return &DataFrameBuilder_NewFromQueryAndRange_Call{Call: _e.mock.On("NewFromQueryAndRange", ctx, begin, end, q, downsample, progress1)}
}

func (_c *DataFrameBuilder_NewFromQueryAndRange_Call) Run(run func(ctx context.Context, begin time.Time, end time.Time, q *query.Query, downsample bool, progress1 progress.Progress)) *DataFrameBuilder_NewFromQueryAndRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *query.Query
		if args[3] != nil {
			arg3 = args[3].(*query.Query)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 progress.Progress
		if args[5] != nil {
			arg5 = args[5].(progress.Progress)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *DataFrameBuilder_NewFromQueryAndRange_Call) Return(dataFrame *dataframe.DataFrame, err error) *DataFrameBuilder_NewFromQueryAndRange_Call {
	_c.Call.Return(dataFrame, err)
	return _c
}

func (_c *DataFrameBuilder_NewFromQueryAndRange_Call) RunAndReturn(run func(ctx context.Context, begin time.Time, end time.Time, q *query.Query, downsample bool, progress1 progress.Progress) (*dataframe.DataFrame, error)) *DataFrameBuilder_NewFromQueryAndRange_Call {
	_c.Call.Return(run)
	return _c
}

// NewNFromKeys provides a mock function for the type DataFrameBuilder
func (_mock *DataFrameBuilder) NewNFromKeys(ctx context.Context, end time.Time, keys []string, n int32, progress1 progress.Progress) (*dataframe.DataFrame, error) {
	ret := _mock.Called(ctx, end, keys, n, progress1)

	if len(ret) == 0 {
		panic("no return value specified for NewNFromKeys")
	}

	var r0 *dataframe.DataFrame
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, []string, int32, progress.Progress) (*dataframe.DataFrame, error)); ok {
		return returnFunc(ctx, end, keys, n, progress1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, []string, int32, progress.Progress) *dataframe.DataFrame); ok {
		r0 = returnFunc(ctx, end, keys, n, progress1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dataframe.DataFrame)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, []string, int32, progress.Progress) error); ok {
		r1 = returnFunc(ctx, end, keys, n, progress1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataFrameBuilder_NewNFromKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewNFromKeys'
type DataFrameBuilder_NewNFromKeys_Call struct {
	*mock.Call
}

// NewNFromKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - end time.Time
//   - keys []string
//   - n int32
//   - progress1 progress.Progress
func (_e *DataFrameBuilder_Expecter) NewNFromKeys(ctx interface{}, end interface{}, keys interface{}, n interface{}, progress1 interface{}) *DataFrameBuilder_NewNFromKeys_Call {
	return &DataFrameBuilder_NewNFromKeys_Call{Call: _e.mock.On("NewNFromKeys", ctx, end, keys, n, progress1)}
}

func (_c *DataFrameBuilder_NewNFromKeys_Call) Run(run func(ctx context.Context, end time.Time, keys []string, n int32, progress1 progress.Progress)) *DataFrameBuilder_NewNFromKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		var arg4 progress.Progress
		if args[4] != nil {
			arg4 = args[4].(progress.Progress)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *DataFrameBuilder_NewNFromKeys_Call) Return(dataFrame *dataframe.DataFrame, err error) *DataFrameBuilder_NewNFromKeys_Call {
	_c.Call.Return(dataFrame, err)
	return _c
}

func (_c *DataFrameBuilder_NewNFromKeys_Call) RunAndReturn(run func(ctx context.Context, end time.Time, keys []string, n int32, progress1 progress.Progress) (*dataframe.DataFrame, error)) *DataFrameBuilder_NewNFromKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewNFromQuery provides a mock function for the type DataFrameBuilder
func (_mock *DataFrameBuilder) NewNFromQuery(ctx context.Context, end time.Time, q *query.Query, n int32, progress1 progress.Progress) (*dataframe.DataFrame, error) {
	ret := _mock.Called(ctx, end, q, n, progress1)

	if len(ret) == 0 {
		panic("no return value specified for NewNFromQuery")
	}

	var r0 *dataframe.DataFrame
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, *query.Query, int32, progress.Progress) (*dataframe.DataFrame, error)); ok {
		return returnFunc(ctx, end, q, n, progress1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, *query.Query, int32, progress.Progress) *dataframe.DataFrame); ok {
		r0 = returnFunc(ctx, end, q, n, progress1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dataframe.DataFrame)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, *query.Query, int32, progress.Progress) error); ok {
		r1 = returnFunc(ctx, end, q, n, progress1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataFrameBuilder_NewNFromQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewNFromQuery'
type DataFrameBuilder_NewNFromQuery_Call struct {
	*mock.Call
}

// NewNFromQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - end time.Time
//   - q *query.Query
//   - n int32
//   - progress1 progress.Progress
func (_e *DataFrameBuilder_Expecter) NewNFromQuery(ctx interface{}, end interface{}, q interface{}, n interface{}, progress1 interface{}) *DataFrameBuilder_NewNFromQuery_Call {
	return &DataFrameBuilder_NewNFromQuery_Call{Call: _e.mock.On("NewNFromQuery", ctx, end, q, n, progress1)}
}

func (_c *DataFrameBuilder_NewNFromQuery_Call) Run(run func(ctx context.Context, end time.Time, q *query.Query, n int32, progress1 progress.Progress)) *DataFrameBuilder_NewNFromQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 *query.Query
		if args[2] != nil {
			arg2 = args[2].(*query.Query)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		var arg4 progress.Progress
		if args[4] != nil {
			arg4 = args[4].(progress.Progress)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *DataFrameBuilder_NewNFromQuery_Call) Return(dataFrame *dataframe.DataFrame, err error) *DataFrameBuilder_NewNFromQuery_Call {
	_c.Call.Return(dataFrame, err)
	return _c
}

func (_c *DataFrameBuilder_NewNFromQuery_Call) RunAndReturn(run func(ctx context.Context, end time.Time, q *query.Query, n int32, progress1 progress.Progress) (*dataframe.DataFrame, error)) *DataFrameBuilder_NewNFromQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NumMatches provides a mock function for the type DataFrameBuilder
func (_mock *DataFrameBuilder) NumMatches(ctx context.Context, q *query.Query) (int64, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for NumMatches")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *query.Query) (int64, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *query.Query) int64); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *query.Query) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataFrameBuilder_NumMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NumMatches'
type DataFrameBuilder_NumMatches_Call struct {
	*mock.Call
}

// NumMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.Query
func (_e *DataFrameBuilder_Expecter) NumMatches(ctx interface{}, q interface{}) *DataFrameBuilder_NumMatches_Call {
	return &DataFrameBuilder_NumMatches_Call{Call: _e.mock.On("NumMatches", ctx, q)}
}

func (_c *DataFrameBuilder_NumMatches_Call) Run(run func(ctx context.Context, q *query.Query)) *DataFrameBuilder_NumMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *query.Query
		if args[1] != nil {
			arg1 = args[1].(*query.Query)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DataFrameBuilder_NumMatches_Call) Return(n int64, err error) *DataFrameBuilder_NumMatches_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *DataFrameBuilder_NumMatches_Call) RunAndReturn(run func(ctx context.Context, q *query.Query) (int64, error)) *DataFrameBuilder_NumMatches_Call {
	_c.Call.Return(run)
	return _c
}

// PreflightQuery provides a mock function for the type DataFrameBuilder
func (_mock *DataFrameBuilder) PreflightQuery(ctx context.Context, q *query.Query, referenceParamSet paramtools.ReadOnlyParamSet) (int64, paramtools.ParamSet, error) {
	ret := _mock.Called(ctx, q, referenceParamSet)

	if len(ret) == 0 {
		panic("no return value specified for PreflightQuery")
	}

	var r0 int64
	var r1 paramtools.ParamSet
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *query.Query, paramtools.ReadOnlyParamSet) (int64, paramtools.ParamSet, error)); ok {
		return returnFunc(ctx, q, referenceParamSet)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *query.Query, paramtools.ReadOnlyParamSet) int64); ok {
		r0 = returnFunc(ctx, q, referenceParamSet)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *query.Query, paramtools.ReadOnlyParamSet) paramtools.ParamSet); ok {
		r1 = returnFunc(ctx, q, referenceParamSet)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(paramtools.ParamSet)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *query.Query, paramtools.ReadOnlyParamSet) error); ok {
		r2 = returnFunc(ctx, q, referenceParamSet)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// DataFrameBuilder_PreflightQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreflightQuery'
type DataFrameBuilder_PreflightQuery_Call struct {
	*mock.Call
}

// PreflightQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - q *query.Query
//   - referenceParamSet paramtools.ReadOnlyParamSet
func (_e *DataFrameBuilder_Expecter) PreflightQuery(ctx interface{}, q interface{}, referenceParamSet interface{}) *DataFrameBuilder_PreflightQuery_Call {
	return &DataFrameBuilder_PreflightQuery_Call{Call: _e.mock.On("PreflightQuery", ctx, q, referenceParamSet)}
}

func (_c *DataFrameBuilder_PreflightQuery_Call) Run(run func(ctx context.Context, q *query.Query, referenceParamSet paramtools.ReadOnlyParamSet)) *DataFrameBuilder_PreflightQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *query.Query
		if args[1] != nil {
			arg1 = args[1].(*query.Query)
		}
		var arg2 paramtools.ReadOnlyParamSet
		if args[2] != nil {
			arg2 = args[2].(paramtools.ReadOnlyParamSet)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DataFrameBuilder_PreflightQuery_Call) Return(n int64, paramSet paramtools.ParamSet, err error) *DataFrameBuilder_PreflightQuery_Call {
	_c.Call.Return(n, paramSet, err)
	return _c
}

func (_c *DataFrameBuilder_PreflightQuery_Call) RunAndReturn(run func(ctx context.Context, q *query.Query, referenceParamSet paramtools.ReadOnlyParamSet) (int64, paramtools.ParamSet, error)) *DataFrameBuilder_PreflightQuery_Call {
	_c.Call.Return(run)
	return _c
}
