global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9000

rule_files:
  - "alert.rules"
  - "absent.rules"

scrape_configs:
  - job_name: 'collectd'
    static_configs:
      - targets: ['skia-monitoring:20002']

  - job_name: 'corpproxy'
    static_configs:
      - targets: ['skia-proxy:20000']

  - job_name: 'logmetrics'
    static_configs:
      - targets: ['skia-monitoring:20001']

  - job_name: 'probeserver'
    static_configs:
      - targets: ['skia-monitoring:20000']

  - job_name: 'datastore_backup'
    static_configs:
      - targets: ['skia-monitoring:20005']

  - job_name: 'alert-to-pubsub'
    static_configs:
      - targets: ['skia-prom:20007']

  - job_name: 'push'
    static_configs:
      - targets: ['skia-push:20000']

# pulld for every server.
  - job_name: 'pulld'
    static_configs:
      - targets: ['skia-monitoring:11000']
      - targets: ['skia-monitoring:11000']
      - targets: ['skia-prom:11000']
      - targets: ['skia-proxy:11000']
      - targets: ['skia-push:11000']
      - targets: ['skia-skfe-1:11000']
      - targets: ['skia-skfe-2:11000']

  # Prometheus self monitoring.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['skia-prom:8000']

  - job_name: 'proxy_with_auth'
    static_configs:
      - targets: ['skia-prom:20002']

  - job_name: 'webhook_proxy'
    static_configs:
      - targets: ['skia-prom:20004']

  # Gateways
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['localhost:20006']

  # Federation
  - job_name: 'federate'
    scrape_interval: 30s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job=~".+"}'

    static_configs:
      - targets:
        - 'localhost:12001'
        labels:
          federated: 'jumphost-rpi-01'
      - targets:
        - 'localhost:12002'
        labels:
          federated: 'jumphost-linux-01'
      - targets:
        - 'localhost:12003'
        labels:
          federated: 'jumphost-win-02'
      - targets:
        - 'localhost:12004'
        labels:
          federated: 'jumphost-win-03'
      - targets:
        - 'localhost:12005'
        labels:
          federated: 'jumphost-internal-01'
