global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:8001

rule_files:
  - "alert.rules"
  - "absent.rules"

scrape_configs:
  - job_name: 'androidingest'
    static_configs:
      - targets: ['skia-android-ingest:20000']
      - targets: ['skia-android-ingest:20001']

  - job_name: 'autoroll'
    static_configs:
      - targets: ['android-master-autoroll:20000']
      - targets: ['android-o-autoroll:20000']
      - targets: ['angle-chromium-autoroll:20000']
      - targets: ['angle-skia-autoroll:20000']
      - targets: ['skia-autoroll:20000']
      - targets: ['skia-internal-autoroll:20000']
      - targets: ['catapult-autoroll:20000']
      - targets: ['depot-tools-chromium-autoroll:20000']
      - targets: ['google3-autoroll:20000']
      - targets: ['nacl-autoroll:20000']
      - targets: ['pdfium-autoroll:20000']
      - targets: ['fuchsia-autoroll:20000']
      - targets: ['src-internal-chromium-autoroll:20000']
      - targets: ['webrtc-chromium-autoroll:20000']

  - job_name: 'collectd'
    static_configs:
      - targets: ['skia-monitoring:20002']

  - job_name: 'contest'
    static_configs:
      - targets: ['skia-docs:20001']

  - job_name: 'corpproxy'
    static_configs:
      - targets: ['skia-proxy:20000']

  - job_name: 'coverage'
    static_configs:
      - targets: ['skia-coverage:20000']

  - job_name: 'ct-pixel-diff'
    static_configs:
      - targets: ['skia-ct-pixel-diff:20000']

  - job_name: 'ct-poller'
    static_configs:
      - targets: ['skia-ct-master:20000']

  - job_name: 'ctfe'
    static_configs:
      - targets: ['skia-ctfe:20000']

  - job_name: 'cq_watcher'
    static_configs:
      - targets: ['skia-cq-watcher:20000']

  - job_name: 'debugger'
    static_configs:
      - targets: ['skia-debugger:20000']

  - job_name: 'datahopper'
    static_configs:
      - targets: ['skia-datahopper2:20000']

  - job_name: 'diffserver'
    static_configs:
      - targets: ['skia-diffserver-prod:20000']
      - targets: ['skia-diffserver-stage:20000']

  - job_name: 'docserver'
    static_configs:
      - targets: ['skia-docs:20000']

  - job_name: 'fiddle'
    static_configs:
      - targets: ['skia-fiddle:20000']

  - job_name: 'fuzzer-be'
    static_configs:
      - targets: ['skia-fuzzer-be-1:20000']
      - targets: ['skia-fuzzer-be-2:20000']
      - targets: ['skia-fuzzer-be-3:20000']

  - job_name: 'fuzzer-fe'
    static_configs:
      - targets: ['skia-fuzzer-fe:20000']

  - job_name: 'gold'
    static_configs:
      - targets: ['skia-gold-pdfium:20001']
      - targets: ['skia-gold-prod:20001']
      - targets: ['skia-gold-stage:20001']
      - targets: ['skia-gold-public:20001']

  - job_name: 'ingestion'
    static_configs:
      - targets: ['skia-ingestion:20000']
        labels:
          corpus: gold
      - targets: ['skia-ingestion:20001']
        labels:
          corpus: pdfium_gold
      - targets: ['skia-ingestion:20002']
        labels:
          corpus: chromevr_gold

  - job_name: 'leasing'
    static_configs:
      - targets: ['skia-leasing:20000']

  - job_name: 'logmetrics'
    static_configs:
      - targets: ['skia-monitoring:20001']

  - job_name: 'proberd'
    static_configs:
      - targets: ['skia-monitoring:20000']

  - job_name: 'datastore-backup'
    static_configs:
      - targets: ['skia-monitoring:20005']

  - job_name: 'push'
    static_configs:
      - targets: ['skia-push:20000']

  - job_name: 'skiaperfd'
    static_configs:
      - targets: ['skia-perf:20000']
      - targets: ['skia-android-perf:20000']
        labels:
          subdomain: android-perf
      - targets: ['skia-android-master-perf:20000']
        labels:
          subdomain: android-master-perf

  - job_name: 'status'
    static_configs:
      - targets: ['skia-status:20000']
      - targets: ['skia-status-internal:20000']

  - job_name: 'swarming_logger'
    static_configs:
      - targets: ['skia-swarming-logger:20000']

  - job_name: 'task_scheduler'
    static_configs:
      - targets: ['skia-task-scheduler:20000']
      - targets: ['skia-task-scheduler-internal:20000']

  - job_name: 'traceserver'
    static_configs:
      - targets: ['skia-tracedb:20003']
        labels:
          corpus: pdfium_gold
      - targets: ['skia-tracedb:20004']
        labels:
          corpus: gold
      - targets: ['skia-tracedb:20005']
        labels:
          corpus: chromevr_gold

# pulld for every server.
  - job_name: 'pulld'
    static_configs:
      - targets: ['android-master-autoroll:11000']
      - targets: ['android-o-autoroll:11000']
      - targets: ['angle-chromium-autoroll:11000']
      - targets: ['angle-skia-autoroll:11000']
      - targets: ['google3-autoroll:11000']
      - targets: ['catapult-autoroll:11000']
      - targets: ['depot-tools-chromium-autoroll:11000']
      - targets: ['nacl-autoroll:11000']
      - targets: ['pdfium-autoroll:11000']
      - targets: ['fuchsia-autoroll:11000']
      - targets: ['skia-android-ingest:11000']
      - targets: ['skia-android-perf:11000']
      - targets: ['skia-android-master-perf:11000']
      - targets: ['skia-autoroll:11000']
      - targets: ['skia-ct-pixel-diff:11000']
      - targets: ['skia-cq-watcher:11000']
      - targets: ['skia-datahopper2:11000']
      - targets: ['skia-debugger:11000']
      - targets: ['skia-diffserver-prod:11000']
      - targets: ['skia-diffserver-stage:11000']
      - targets: ['skia-docs:11000']
      - targets: ['skia-fiddle:11000']
      - targets: ['skia-fuzzer-be-1:11000']
      - targets: ['skia-fuzzer-be-2:11000']
      - targets: ['skia-fuzzer-be-3:11000']
      - targets: ['skia-fuzzer-fe:11000']
      - targets: ['skia-gold-pdfium:11000']
      - targets: ['skia-gold-prod:11000']
      - targets: ['skia-internal:11000']
      - targets: ['skia-monitoring:11000']
      - targets: ['skia-monitoring:11000']
      - targets: ['skia-perf:11000']
      - targets: ['skia-prom:11000']
      - targets: ['skia-proxy:11000']
      - targets: ['skia-push:11000']
      - targets: ['skia-skfe-1:11000']
      - targets: ['skia-skfe-2:11000']
      - targets: ['skia-status:11000']
      - targets: ['skia-swarming-logger:11000']
      - targets: ['skia-task-scheduler-internal:11000']
      - targets: ['skia-task-scheduler:11000']
      - targets: ['skia-tracedb:11000']
      - targets: ['src-internal-chromium-autoroll:11000']
      - targets: ['webrtc-chromium-autoroll:11000']

  # Prometheus self monitoring.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['skia-prom:8000']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['skia-prom:8001']

  - job_name: 'prom-proxy'
    static_configs:
      - targets: ['skia-prom:20002']

  - job_name: 'alert-proxy'
    static_configs:
      - targets: ['skia-prom:20003']

  - job_name: 'webhook-proxy'
    static_configs:
      - targets: ['skia-prom:20004']

  # Gateways
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['localhost:20006']

  # Federation
  - job_name: 'federate'
    scrape_interval: 30s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job=~".+"}'

    static_configs:
      - targets:
        - 'localhost:12001'
        labels:
          federated: 'jumphost-rpi-01'
      - targets:
        - 'localhost:12002'
        labels:
          federated: 'jumphost-linux-01'
