// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.skia.org/infra/perf/go/trybot"
	"go.skia.org/infra/perf/go/trybot/store"
	"go.skia.org/infra/perf/go/types"
)

// NewTryBotStore creates a new instance of TryBotStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTryBotStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TryBotStore {
	mock := &TryBotStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TryBotStore is an autogenerated mock type for the TryBotStore type
type TryBotStore struct {
	mock.Mock
}

type TryBotStore_Expecter struct {
	mock *mock.Mock
}

func (_m *TryBotStore) EXPECT() *TryBotStore_Expecter {
	return &TryBotStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type TryBotStore
func (_mock *TryBotStore) Get(ctx context.Context, cl types.CL, patch int) ([]store.GetResult, error) {
	ret := _mock.Called(ctx, cl, patch)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []store.GetResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.CL, int) ([]store.GetResult, error)); ok {
		return returnFunc(ctx, cl, patch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.CL, int) []store.GetResult); ok {
		r0 = returnFunc(ctx, cl, patch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.GetResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.CL, int) error); ok {
		r1 = returnFunc(ctx, cl, patch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TryBotStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TryBotStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - cl types.CL
//   - patch int
func (_e *TryBotStore_Expecter) Get(ctx interface{}, cl interface{}, patch interface{}) *TryBotStore_Get_Call {
	return &TryBotStore_Get_Call{Call: _e.mock.On("Get", ctx, cl, patch)}
}

func (_c *TryBotStore_Get_Call) Run(run func(ctx context.Context, cl types.CL, patch int)) *TryBotStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.CL
		if args[1] != nil {
			arg1 = args[1].(types.CL)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TryBotStore_Get_Call) Return(getResults []store.GetResult, err error) *TryBotStore_Get_Call {
	_c.Call.Return(getResults, err)
	return _c
}

func (_c *TryBotStore_Get_Call) RunAndReturn(run func(ctx context.Context, cl types.CL, patch int) ([]store.GetResult, error)) *TryBotStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type TryBotStore
func (_mock *TryBotStore) List(ctx context.Context, since time.Time) ([]store.ListResult, error) {
	ret := _mock.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []store.ListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]store.ListResult, error)); ok {
		return returnFunc(ctx, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []store.ListResult); ok {
		r0 = returnFunc(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TryBotStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TryBotStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
func (_e *TryBotStore_Expecter) List(ctx interface{}, since interface{}) *TryBotStore_List_Call {
	return &TryBotStore_List_Call{Call: _e.mock.On("List", ctx, since)}
}

func (_c *TryBotStore_List_Call) Run(run func(ctx context.Context, since time.Time)) *TryBotStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TryBotStore_List_Call) Return(listResults []store.ListResult, err error) *TryBotStore_List_Call {
	_c.Call.Return(listResults, err)
	return _c
}

func (_c *TryBotStore_List_Call) RunAndReturn(run func(ctx context.Context, since time.Time) ([]store.ListResult, error)) *TryBotStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type TryBotStore
func (_mock *TryBotStore) Write(ctx context.Context, tryFile trybot.TryFile) error {
	ret := _mock.Called(ctx, tryFile)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, trybot.TryFile) error); ok {
		r0 = returnFunc(ctx, tryFile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TryBotStore_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type TryBotStore_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - tryFile trybot.TryFile
func (_e *TryBotStore_Expecter) Write(ctx interface{}, tryFile interface{}) *TryBotStore_Write_Call {
	return &TryBotStore_Write_Call{Call: _e.mock.On("Write", ctx, tryFile)}
}

func (_c *TryBotStore_Write_Call) Run(run func(ctx context.Context, tryFile trybot.TryFile)) *TryBotStore_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 trybot.TryFile
		if args[1] != nil {
			arg1 = args[1].(trybot.TryFile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TryBotStore_Write_Call) Return(err error) *TryBotStore_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TryBotStore_Write_Call) RunAndReturn(run func(ctx context.Context, tryFile trybot.TryFile) error) *TryBotStore_Write_Call {
	_c.Call.Return(run)
	return _c
}
