// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
	"go.skia.org/infra/go/alogin"
	"go.skia.org/infra/go/roles"
)

// NewLogin creates a new instance of Login. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogin(t interface {
	mock.TestingT
	Cleanup(func())
}) *Login {
	mock := &Login{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Login is an autogenerated mock type for the Login type
type Login struct {
	mock.Mock
}

type Login_Expecter struct {
	mock *mock.Mock
}

func (_m *Login) EXPECT() *Login_Expecter {
	return &Login_Expecter{mock: &_m.Mock}
}

// HasRole provides a mock function for the type Login
func (_mock *Login) HasRole(r *http.Request, role roles.Role) bool {
	ret := _mock.Called(r, role)

	if len(ret) == 0 {
		panic("no return value specified for HasRole")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*http.Request, roles.Role) bool); ok {
		r0 = returnFunc(r, role)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Login_HasRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRole'
type Login_HasRole_Call struct {
	*mock.Call
}

// HasRole is a helper method to define mock.On call
//   - r *http.Request
//   - role roles.Role
func (_e *Login_Expecter) HasRole(r interface{}, role interface{}) *Login_HasRole_Call {
	return &Login_HasRole_Call{Call: _e.mock.On("HasRole", r, role)}
}

func (_c *Login_HasRole_Call) Run(run func(r *http.Request, role roles.Role)) *Login_HasRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 roles.Role
		if args[1] != nil {
			arg1 = args[1].(roles.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Login_HasRole_Call) Return(b bool) *Login_HasRole_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Login_HasRole_Call) RunAndReturn(run func(r *http.Request, role roles.Role) bool) *Login_HasRole_Call {
	_c.Call.Return(run)
	return _c
}

// LoggedInAs provides a mock function for the type Login
func (_mock *Login) LoggedInAs(r *http.Request) alogin.EMail {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for LoggedInAs")
	}

	var r0 alogin.EMail
	if returnFunc, ok := ret.Get(0).(func(*http.Request) alogin.EMail); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(alogin.EMail)
	}
	return r0
}

// Login_LoggedInAs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoggedInAs'
type Login_LoggedInAs_Call struct {
	*mock.Call
}

// LoggedInAs is a helper method to define mock.On call
//   - r *http.Request
func (_e *Login_Expecter) LoggedInAs(r interface{}) *Login_LoggedInAs_Call {
	return &Login_LoggedInAs_Call{Call: _e.mock.On("LoggedInAs", r)}
}

func (_c *Login_LoggedInAs_Call) Run(run func(r *http.Request)) *Login_LoggedInAs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Login_LoggedInAs_Call) Return(eMail alogin.EMail) *Login_LoggedInAs_Call {
	_c.Call.Return(eMail)
	return _c
}

func (_c *Login_LoggedInAs_Call) RunAndReturn(run func(r *http.Request) alogin.EMail) *Login_LoggedInAs_Call {
	_c.Call.Return(run)
	return _c
}

// LoginURL provides a mock function for the type Login
func (_mock *Login) LoginURL(r *http.Request) string {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for LoginURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Login_LoginURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginURL'
type Login_LoginURL_Call struct {
	*mock.Call
}

// LoginURL is a helper method to define mock.On call
//   - r *http.Request
func (_e *Login_Expecter) LoginURL(r interface{}) *Login_LoginURL_Call {
	return &Login_LoginURL_Call{Call: _e.mock.On("LoginURL", r)}
}

func (_c *Login_LoginURL_Call) Run(run func(r *http.Request)) *Login_LoginURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Login_LoginURL_Call) Return(s string) *Login_LoginURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Login_LoginURL_Call) RunAndReturn(run func(r *http.Request) string) *Login_LoginURL_Call {
	_c.Call.Return(run)
	return _c
}

// Roles provides a mock function for the type Login
func (_mock *Login) Roles(r *http.Request) roles.Roles {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Roles")
	}

	var r0 roles.Roles
	if returnFunc, ok := ret.Get(0).(func(*http.Request) roles.Roles); ok {
		r0 = returnFunc(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(roles.Roles)
		}
	}
	return r0
}

// Login_Roles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Roles'
type Login_Roles_Call struct {
	*mock.Call
}

// Roles is a helper method to define mock.On call
//   - r *http.Request
func (_e *Login_Expecter) Roles(r interface{}) *Login_Roles_Call {
	return &Login_Roles_Call{Call: _e.mock.On("Roles", r)}
}

func (_c *Login_Roles_Call) Run(run func(r *http.Request)) *Login_Roles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Login_Roles_Call) Return(roles1 roles.Roles) *Login_Roles_Call {
	_c.Call.Return(roles1)
	return _c
}

func (_c *Login_Roles_Call) RunAndReturn(run func(r *http.Request) roles.Roles) *Login_Roles_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type Login
func (_mock *Login) Status(r *http.Request) alogin.Status {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 alogin.Status
	if returnFunc, ok := ret.Get(0).(func(*http.Request) alogin.Status); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(alogin.Status)
	}
	return r0
}

// Login_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type Login_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - r *http.Request
func (_e *Login_Expecter) Status(r interface{}) *Login_Status_Call {
	return &Login_Status_Call{Call: _e.mock.On("Status", r)}
}

func (_c *Login_Status_Call) Run(run func(r *http.Request)) *Login_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Login_Status_Call) Return(status alogin.Status) *Login_Status_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *Login_Status_Call) RunAndReturn(run func(r *http.Request) alogin.Status) *Login_Status_Call {
	_c.Call.Return(run)
	return _c
}
