// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.goldmine.build/go/paramtools"
	"go.goldmine.build/perf/go/types"
)

// NewOPSProvider creates a new instance of OPSProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOPSProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *OPSProvider {
	mock := &OPSProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OPSProvider is an autogenerated mock type for the OPSProvider type
type OPSProvider struct {
	mock.Mock
}

type OPSProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *OPSProvider) EXPECT() *OPSProvider_Expecter {
	return &OPSProvider_Expecter{mock: &_m.Mock}
}

// GetLatestTile provides a mock function for the type OPSProvider
func (_mock *OPSProvider) GetLatestTile(context1 context.Context) (types.TileNumber, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestTile")
	}

	var r0 types.TileNumber
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (types.TileNumber, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) types.TileNumber); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(types.TileNumber)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OPSProvider_GetLatestTile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestTile'
type OPSProvider_GetLatestTile_Call struct {
	*mock.Call
}

// GetLatestTile is a helper method to define mock.On call
//   - context1 context.Context
func (_e *OPSProvider_Expecter) GetLatestTile(context1 interface{}) *OPSProvider_GetLatestTile_Call {
	return &OPSProvider_GetLatestTile_Call{Call: _e.mock.On("GetLatestTile", context1)}
}

func (_c *OPSProvider_GetLatestTile_Call) Run(run func(context1 context.Context)) *OPSProvider_GetLatestTile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OPSProvider_GetLatestTile_Call) Return(tileNumber types.TileNumber, err error) *OPSProvider_GetLatestTile_Call {
	_c.Call.Return(tileNumber, err)
	return _c
}

func (_c *OPSProvider_GetLatestTile_Call) RunAndReturn(run func(context1 context.Context) (types.TileNumber, error)) *OPSProvider_GetLatestTile_Call {
	_c.Call.Return(run)
	return _c
}

// GetParamSet provides a mock function for the type OPSProvider
func (_mock *OPSProvider) GetParamSet(ctx context.Context, tileNumber types.TileNumber) (paramtools.ReadOnlyParamSet, error) {
	ret := _mock.Called(ctx, tileNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetParamSet")
	}

	var r0 paramtools.ReadOnlyParamSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.TileNumber) (paramtools.ReadOnlyParamSet, error)); ok {
		return returnFunc(ctx, tileNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.TileNumber) paramtools.ReadOnlyParamSet); ok {
		r0 = returnFunc(ctx, tileNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(paramtools.ReadOnlyParamSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.TileNumber) error); ok {
		r1 = returnFunc(ctx, tileNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OPSProvider_GetParamSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParamSet'
type OPSProvider_GetParamSet_Call struct {
	*mock.Call
}

// GetParamSet is a helper method to define mock.On call
//   - ctx context.Context
//   - tileNumber types.TileNumber
func (_e *OPSProvider_Expecter) GetParamSet(ctx interface{}, tileNumber interface{}) *OPSProvider_GetParamSet_Call {
	return &OPSProvider_GetParamSet_Call{Call: _e.mock.On("GetParamSet", ctx, tileNumber)}
}

func (_c *OPSProvider_GetParamSet_Call) Run(run func(ctx context.Context, tileNumber types.TileNumber)) *OPSProvider_GetParamSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.TileNumber
		if args[1] != nil {
			arg1 = args[1].(types.TileNumber)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OPSProvider_GetParamSet_Call) Return(readOnlyParamSet paramtools.ReadOnlyParamSet, err error) *OPSProvider_GetParamSet_Call {
	_c.Call.Return(readOnlyParamSet, err)
	return _c
}

func (_c *OPSProvider_GetParamSet_Call) RunAndReturn(run func(ctx context.Context, tileNumber types.TileNumber) (paramtools.ReadOnlyParamSet, error)) *OPSProvider_GetParamSet_Call {
	_c.Call.Return(run)
	return _c
}
