all:
  vars:
    # The user under which we run our services:
    skolo_account: chrome-bot
    # That user's primary group:
    skolo_group: chrome-bot

    win_python3_path: C:\Python39

    all:
      # The port on which each app publishes Prometheus metrics.
      prometheus:
        web_server_port: 8000
        alert_to_pubsub_port: 8001
        version: '2.29.1'
        monitoring:
          ports:
            metadata_server_ansible: 20010
            router_backup_ansible: 20011
            powercycle_server_ansible: 20012
            alert_to_pubsub_ansible: 20013
            test_machine_monitor: 20014
            collectd: 20015

      # The port that the metadata server is serving on.
      metadata_server_port: 9000

      # The root of the skiabot repo.
      repo_root: '{{ inventory_dir }}/../../'

  children:
    jumphosts:
      hosts:
        rack1:
          install_metadata_server__service_account_name: skolo-service-accounts
        rack2:
          install_metadata_server__service_account_name: skolo-service-accounts
        rack3:
          install_metadata_server__service_account_name: skolo-service-accounts
        rack4:
          install_metadata_server__service_account_name: skolo-service-accounts
        rack5:
          install_metadata_server__service_account_name: skolo-internal-service-account
      vars:
        copy_service_account_key__name: skolo-jumphost

    routers:
      hosts:
        router-rack1:
          copy_authorized_keys__jumphost: rack1
        router-rack2:
          copy_authorized_keys__jumphost: rack2
        router-rack3:
          copy_authorized_keys__jumphost: rack3
        router-rack4:
          copy_authorized_keys__jumphost: rack4
        router-rack5:
          copy_authorized_keys__jumphost: rack5
      vars:
        ansible_user: admin
        skolo_account: admin

    gapid_test_machines:
      children:
        rack5_linux:
      vars:
        swarming_needs__needs_mobile_tools: True
        install_test_machine_monitor__start_swarming: True
        install_test_machine_monitor__run_under_desktop: False
        copy_authorized_keys__jumphost: rack5

    switchboard_rpis:
      hosts:
        skia-rpi2-rack4-shelf1-[001:020]:
        skia-rpi2-rack4-shelf1-[025:040]:
        skia-rpi2-rack4-shelf2-[001:024]:
        skia-rpi2-rack4-shelf3-[001:020]:
        skia-rpi2-rack4-shelf4-[001:020]:
      vars:
        swarming_needs__needs_mobile_tools: True
        install_test_machine_monitor__start_swarming: True
        install_test_machine_monitor__run_under_desktop: False
        copy_authorized_keys__jumphost: rack4

    all_linux:
      children:
        rack2_linux:
        rack3_linux:
      vars:
        swarming_needs__needs_mobile_tools: False
        install_test_machine_monitor__start_swarming: True

    # Intentionally left empty because the machines on there are currently managed
    # via the legacy `push` system.
    rack1_machines:

    rack4_machines:
      children:
        switchboard_rpis:

    rpis:
      children:
        rack4_rpis:
        rack1_rpis:

    rack4_rpis:
      children:
        rack4_shelf1:
        rack4_shelf2:
        rack4_shelf3:
        rack4_shelf4:

    rack4_shelf1:
      hosts:
        skia-rpi2-rack4-shelf1-[001:020]:
        skia-rpi2-rack4-shelf1-[025:040]:

    rack4_shelf2:
      hosts:
        skia-rpi2-rack4-shelf2-[001:024]:

    rack4_shelf3:
      hosts:
        skia-rpi2-rack4-shelf3-[001:020]:

    rack4_shelf4:
      hosts:
        skia-rpi2-rack4-shelf4-[001:020]:

    rack1_rpis:
      hosts:
        skia-rpi-001:
        skia-rpi-003:
        skia-rpi-005:
        skia-rpi-009:
        skia-rpi-012:
        skia-rpi-013:
        skia-rpi-014:
        skia-rpi-015:
        skia-rpi-016:
        skia-rpi-018:
        skia-rpi-021:
        skia-rpi-023:
        skia-rpi-026:
        skia-rpi-028:
        skia-rpi-035:
        skia-rpi-037:
        skia-rpi-039:
        skia-rpi-040:
        skia-rpi-045:
        skia-rpi-047:
        skia-rpi-057:
        skia-rpi-058:
        skia-rpi-060:
        skia-rpi-062:
        skia-rpi-067:
        skia-rpi-068:
        skia-rpi-069:
        skia-rpi-070:
        skia-rpi-071:
        skia-rpi-072:
        skia-rpi-073:
        skia-rpi-074:
        skia-rpi-075:
        skia-rpi-076:
      vars:
        ansible_python_interpreter: /usr/bin/python

    rack2_machines:
      children:
        rack2_linux:
        rack2_mac:
        rack2_win:

    rack2_linux:
      hosts:
        skia-e-linux-207:
        skia-e-linux-213:
        skia-e-linux-215:
        skia-e-linux-216:
        skia-e-linux-217:
        skia-e-linux-218:
        skia-e-linux-261:
        skia-e-linux-264:

    rack2_mac:
      hosts:
        skia-e-mac-230:
        skia-e-mac-231:
        skia-e-mac-232:
        skia-e-mac-233:
        skia-e-mac-234:
        skia-e-mac-235:

    rack2_win:
      hosts:
        skia-e-win-201:
        skia-e-win-202:
        skia-e-win-203:
        skia-e-win-204:
        skia-e-win-205:
        skia-e-win-206:
        skia-e-win-210:
        skia-e-win-211:
        skia-e-win-212:
        skia-e-win-240:
        skia-e-win-241:
        skia-e-win-242:
        skia-e-win-243:
        skia-e-win-244:
        skia-e-win-245:
        skia-e-win-246:
        skia-e-win-247:
        skia-e-win-248:
        skia-e-win-249:
        skia-e-win-250:
        skia-e-win-251:
        skia-e-win-252:
        skia-e-win-253:
        skia-e-win-254:
        skia-e-win-255:
      vars:
        ansible_shell_type: powershell

    rack3_machines:
      children:
        rack3_linux:
        rack3_mac:
        rack3_win:

    rack3_linux:
      hosts:
        skia-e-linux-307:
        skia-e-linux-313:
        skia-e-linux-314:
        skia-e-linux-317:
        skia-e-linux-360:
        skia-e-linux-361:
        skia-e-linux-362:
        skia-e-linux-363:
        skia-e-linux-364:
        skia-e-linux-365:
        skia-e-linux-366:

    rack3_mac:
      hosts:
        skia-e-mac-330:
        skia-e-mac-331:
        skia-e-mac-332:
        skia-e-mac-333:
        skia-e-mac-334:
        skia-e-mac-335:
        skia-e-mac-336:

    rack3_win:
      hosts:
        skia-e-win-301:
        skia-e-win-302:
        skia-e-win-304:
        skia-e-win-305:
        skia-e-win-306:
        skia-e-win-310:
        skia-e-win-311:
        skia-e-win-312:
        skia-e-win-341:
        skia-e-win-342:
        skia-e-win-343:
        skia-e-win-344:
        skia-e-win-345:
        skia-e-win-346:
        skia-e-win-347:
        skia-e-win-348:
        skia-e-win-349:
        skia-e-win-353:
        skia-e-win-354:
        skia-e-win-355:
      vars:
        ansible_shell_type: powershell

    rack5_machines:
      children:
        rack5_linux:

    rack5_linux:
      hosts:
        skia-i-gapid-[001:004]:

    all_mac:
      children:
        rack2_mac:
        rack3_mac:
      vars:
        install_test_machine_monitor__start_swarming: True
        skolo_group: staff

    all_win:
      children:
        rack2_win:
        rack3_win:
