- hosts: '{{ variable_hosts }}'
  gather_facts: False
  tasks:
    - name: Copy authorized_keys with owner and permissions
      ansible.builtin.copy:
        src: ../authorized_keys
        dest: /home/chrome-bot/.ssh/authorized_keys
        owner: chrome-bot
        group: chrome-bot
        mode: '0644'
