dir: '{{.InterfaceDir}}/mocks'
structname: '{{.InterfaceName}}'
pkgname: mocks
template: testify
filename: mocks.go
template-data:
  unroll-variadic: true
packages:
  go.goldmine.build/docsyserver/go/codereview:
    interfaces:
      CodeReview: {}
  go.goldmine.build/docsyserver/go/docsy:
    interfaces:
      Docsy: {}
  go.goldmine.build/fiddlek/go/store:
    interfaces:
      Store: {}
  go.goldmine.build/go/allowed:
    interfaces:
      Allow: {}
  go.goldmine.build/go/alogin:
    interfaces:
      Login: {}
  go.goldmine.build/go/chrome_branch:
    interfaces:
      Client: {}
  go.goldmine.build/go/docker:
    interfaces:
      Client: {}
  go.goldmine.build/go/gcs:
    interfaces:
      GCSClient: {}
  go.goldmine.build/go/gerrit:
    interfaces:
      GerritInterface: {}
  go.goldmine.build/go/gitiles:
    interfaces:
      GitilesRepo: {}
  go.goldmine.build/go/gitstore:
    interfaces:
      GitStore: {}
  go.goldmine.build/go/login:
    interfaces:
      OAuthConfig: {}
  go.goldmine.build/go/monorail/v3:
    interfaces:
      IMonorailService: {}
  go.goldmine.build/go/now:
    interfaces:
      TimeTicker: {}
  go.goldmine.build/go/pubsub:
    config: {}
    interfaces:
      Client: {}
      PublishResult: {}
      Snapshot: {}
      Subscription: {}
      Topic: {}
  go.goldmine.build/go/secret:
    interfaces:
      Client: {}
  go.goldmine.build/go/serial:
    interfaces:
      Port: {}
  go.goldmine.build/go/sql/pool:
    interfaces:
      Pool: {}
  go.goldmine.build/go/sser:
    interfaces:
      PeerFinder: {}
      Server: {}
  go.goldmine.build/go/vcsinfo:
    interfaces:
      VCS: {}
  go.goldmine.build/go/vfs:
    interfaces:
      FS: {}
      File: {}
  go.goldmine.build/gold-client/go/gcsuploader:
    interfaces:
      GCSUploader: {}
  go.goldmine.build/gold-client/go/httpclient:
    config:
      dir: '{{.InterfaceDir}}/../mocks'
    interfaces:
      HTTPClient: {}
  go.goldmine.build/gold-client/go/imagedownloader:
    interfaces:
      ImageDownloader: {}
  go.goldmine.build/gold-client/go/imgmatching:
    interfaces:
      Matcher: {}
  go.goldmine.build/golden/cmd/gitilesfollower:
    interfaces:
      GitilesLogger: {}
  go.goldmine.build/golden/go/code_review:
    interfaces:
      ChangelistLandedUpdater: {}
      Client: {}
  go.goldmine.build/golden/go/continuous_integration:
    interfaces:
      Client: {}
  go.goldmine.build/golden/go/diff:
    interfaces:
      Calculator: {}
  go.goldmine.build/golden/go/diff/worker:
    interfaces:
      ImageSource: {}
  go.goldmine.build/golden/go/ignore:
    interfaces:
      Store: {}
  go.goldmine.build/golden/go/ingestion:
    interfaces:
      FileSearcher: {}
      Processor: {}
      Source: {}
      Store: {}
  go.goldmine.build/golden/go/search:
    interfaces:
      API: {}
  go.goldmine.build/golden/go/storage:
    config:
      dir: '{{.InterfaceDir}}/../mocks'
    interfaces:
      GCSClient: {}
  go.goldmine.build/kube/go/authproxy/auth:
    interfaces:
      Auth: {}
  go.goldmine.build/npm-audit-mirror/go/types:
    interfaces:
      Check: {}
      ChecksManager: {}
      IIssueTrackerService: {}
      NpmDB: {}
      ProjectAudit: {}
      ProjectMirror: {}
  go.goldmine.build/perf/go/alerts:
    config:
      dir: '{{.InterfaceDir}}/mock'
    interfaces:
      ConfigProvider: {}
      Store: {}
  go.goldmine.build/perf/go/dataframe:
    interfaces:
      DataFrameBuilder: {}
  go.goldmine.build/perf/go/git:
    interfaces:
      Git: {}
  go.goldmine.build/perf/go/graphsshortcut:
    interfaces:
      Store: {}
  go.goldmine.build/perf/go/notify:
    interfaces:
      Notifier: {}
      Transport: {}
  go.goldmine.build/perf/go/perf-tool/application:
    interfaces:
      Application: {}
  go.goldmine.build/perf/go/psrefresh:
    interfaces:
      OPSProvider: {}
  go.goldmine.build/perf/go/regression:
    interfaces:
      Store: {}
  go.goldmine.build/perf/go/shortcut:
    interfaces:
      Store: {}
  go.goldmine.build/perf/go/tracestore:
    interfaces:
      TraceStore: {}
  go.goldmine.build/perf/go/trybot/store:
    interfaces:
      TryBotStore: {}
  go.goldmine.build/scrap/go/scrap:
    interfaces:
      ScrapExchange: {}
  k8s.io/apimachinery/pkg/watch:
    config:
      dir: go/k8s/watch/mocks
    interfaces:
      Interface: {}
  k8s.io/client-go/kubernetes:
    config:
      dir: go/sser/mocks
    interfaces:
      Interface: {}
  k8s.io/client-go/kubernetes/typed/core/v1:
    config:
      dir: go/k8s/mocks
    interfaces:
      CoreV1Interface: {}
      PodInterface: {}
