#!/bin/bash

set -Eexuo pipefail

REL=$(dirname "$BASH_SOURCE")
TAG=`${REL}/../bash/release_tag.sh`

cd ./base
docker build -t base .
docker tag base:latest ghcr.io/goldmine-build/base:${TAG}
docker push ghcr.io/goldmine-build/base:${TAG}

echo ghcr.io/goldmine-build/base:${TAG}