# Configures a jumphost with everything it needs.
- hosts: jumphosts
  user: chrome-bot
  gather_facts: yes
  vars:
    router_backup_ansible_version_override: ''

  roles:
    - copy_authorized_keys
    - copy_service_account_key
    - install_collectd
    - install_metadata_server
    - install_powercycle_server
    - role: install_router_backup
      router_backup_ansible_version:
        '{{ router_backup_ansible_version_override }}'
    - install_prometheus_and_alert_to_pubsub
