# Configures a jumphost with everything it needs.
- hosts: jumphosts
  user: chrome-bot
  gather_facts: yes

  roles:
    - copy_authorized_keys
    - copy_service_account_key
    - install_collectd
    - install_metadata_server
    - install_powercycle_server
    - install_router_backup
    - install_prometheus_and_alert_to_pubsub
