# Configures a jumphost with everything it needs.
- hosts: "{{ variable_hosts | default('jumphosts') }}"
  user: chrome-bot
  gather_facts: yes

  roles:
    - copy_authorized_keys
    - copy_service_account_key
    - install_collectd
    - install_metadata_server
# TODO(jcgregorio) Add role to install powercycler server.
