# Configures alert-to-pubsub on each jumphost.
#
# See the install_managed_prometheus role for how Prometheus is installed.
#
# The primary jumphost playbook is jumphosts.yaml.
- hosts: jumphosts
  user: chrome-bot
  gather_facts: true
  vars:
    alert_to_pubsub_ansible_version_override: ''

  roles:
    - role: install_alert_to_pubsub
      alert_to_pubsub_ansible_version:
        '{{ alert_to_pubsub_ansible_version_override }}'
