# Configures an RPi with everything it needs to run under switchboard.
- hosts: "{{ variable_hosts | default('switchboard_rpis') }}"
  user: chrome-bot
  gather_facts: yes

  pre_tasks:
    - name: Install applications.
      become: yes
      apt:
        pkg:
          - adb
          - libimobiledevice-utils
          - rsync

  roles:
    - copy_authorized_keys
    - copy_adbkey
    - role: copy_service_account_key
      service_account_name: 'skolo-bot-service-account'
    - install_collectd
    - swarming_needs
    - role: install_test_machine_monitor
      start_swarming: true
