# Configures an RPi with everything it needs to run under switchboard.
- hosts: switchboard_rpis
  user: chrome-bot
  gather_facts: yes
  vars:
    test_machine_monitor_version_override: ''

  roles:
    - copy_authorized_keys
    - copy_adbkey
    - copy_service_account_key
    - install_collectd
    - swarming_needs
    - switchboard_needs
    - role: install_test_machine_monitor
      test_machine_monitor_version:
        '{{ test_machine_monitor_version_override }}'
