- hosts: '{{ variable_hosts }}'
  user: root
  gather_facts: False
  tasks:
    - name: Install applications.
      apt:
        pkg:
          - adb
          - libimobiledevice-utils
          - sudo
          - rsync
          - collectd
          - collectd-core
          - collectd-utils

    - name: Make sure we have a 'sudo' group
      group:
        name: sudo
        state: present

    - name: Allow 'sudo' group to have passwordless sudo
      become: yes
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Add sudo users to sudo group
      become: yes
      user:
        name: 'chrome-bot'
        groups: sudo
        append: yes

    - name: Create chrome-bot user.
      user:
        name: chrome-bot
        groups: plugdev,sudo
        generate_ssh_key: true
        shell: /bin/bash

    - name: Configure collectd
      copy:
        src: ../raspberry-pi/collectd.conf
        dest: /etc/collectd/collectd.conf
        owner: root
        group: root
        mode: 0644

    - name: Copy authorized_keys with owner and permissions
      ansible.builtin.copy:
        src: ../authorized_keys
        dest: /home/chrome-bot/.ssh/authorized_keys
        owner: chrome-bot
        group: chrome-bot
        mode: '0644'
