---
- name:
    make temp directory for service account key and trigger `clean_up_tempfile`.
  delegate_to: 127.0.0.1
  tempfile:
    state: directory
  register: service_account_key
  notify: clean_up_tempfile

- name: Extract service account key
  delegate_to: 127.0.0.1
  command:
    argv:
      - '{{ all.repo_root }}/kube/secrets/get-secret-at-path.sh'
      - etc
      - '{{ copy_service_account_key.name }}'
      - '.data."key.json"'
      - '{{ service_account_key.path }}/application_default_credentials.json'
    creates:
      '{{ service_account_key.path }}/application_default_credentials.json'

- name: Copy service account key
  copy:
    src: '{{ service_account_key.path }}/application_default_credentials.json'
    dest: /home/{{ skolo_account }}/.config/gcloud/
    owner: '{{ skolo_account }}'
    group: '{{ skolo_account }}'
    mode: '0644'
