// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.skia.org/infra/go/paramtools"
	"go.skia.org/infra/golden/go/types"
)

// NewCalculator creates a new instance of Calculator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCalculator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Calculator {
	mock := &Calculator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Calculator is an autogenerated mock type for the Calculator type
type Calculator struct {
	mock.Mock
}

type Calculator_Expecter struct {
	mock *mock.Mock
}

func (_m *Calculator) EXPECT() *Calculator_Expecter {
	return &Calculator_Expecter{mock: &_m.Mock}
}

// CalculateDiffs provides a mock function for the type Calculator
func (_mock *Calculator) CalculateDiffs(ctx context.Context, grouping paramtools.Params, additional []types.Digest) error {
	ret := _mock.Called(ctx, grouping, additional)

	if len(ret) == 0 {
		panic("no return value specified for CalculateDiffs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, paramtools.Params, []types.Digest) error); ok {
		r0 = returnFunc(ctx, grouping, additional)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Calculator_CalculateDiffs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateDiffs'
type Calculator_CalculateDiffs_Call struct {
	*mock.Call
}

// CalculateDiffs is a helper method to define mock.On call
//   - ctx context.Context
//   - grouping paramtools.Params
//   - additional []types.Digest
func (_e *Calculator_Expecter) CalculateDiffs(ctx interface{}, grouping interface{}, additional interface{}) *Calculator_CalculateDiffs_Call {
	return &Calculator_CalculateDiffs_Call{Call: _e.mock.On("CalculateDiffs", ctx, grouping, additional)}
}

func (_c *Calculator_CalculateDiffs_Call) Run(run func(ctx context.Context, grouping paramtools.Params, additional []types.Digest)) *Calculator_CalculateDiffs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 paramtools.Params
		if args[1] != nil {
			arg1 = args[1].(paramtools.Params)
		}
		var arg2 []types.Digest
		if args[2] != nil {
			arg2 = args[2].([]types.Digest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Calculator_CalculateDiffs_Call) Return(err error) *Calculator_CalculateDiffs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Calculator_CalculateDiffs_Call) RunAndReturn(run func(ctx context.Context, grouping paramtools.Params, additional []types.Digest) error) *Calculator_CalculateDiffs_Call {
	_c.Call.Return(run)
	return _c
}
