// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.skia.org/infra/go/chrome_branch"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type Client
func (_mock *Client) Get(context1 context.Context) (*chrome_branch.Branches, []*chrome_branch.Branch, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *chrome_branch.Branches
	var r1 []*chrome_branch.Branch
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*chrome_branch.Branches, []*chrome_branch.Branch, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *chrome_branch.Branches); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chrome_branch.Branches)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) []*chrome_branch.Branch); ok {
		r1 = returnFunc(context1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*chrome_branch.Branch)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(context1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Client_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Client_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Client_Expecter) Get(context1 interface{}) *Client_Get_Call {
	return &Client_Get_Call{Call: _e.mock.On("Get", context1)}
}

func (_c *Client_Get_Call) Run(run func(context1 context.Context)) *Client_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_Get_Call) Return(branches *chrome_branch.Branches, branchs []*chrome_branch.Branch, err error) *Client_Get_Call {
	_c.Call.Return(branches, branchs, err)
	return _c
}

func (_c *Client_Get_Call) RunAndReturn(run func(context1 context.Context) (*chrome_branch.Branches, []*chrome_branch.Branch, error)) *Client_Get_Call {
	_c.Call.Return(run)
	return _c
}
