- hosts: all
  connection: local
  remote_user: chrome-bot
  become_user: root
  become: yes
  become_method: sudo

  tasks:
    - name: Remove normal nfs rule for staging
      lineinfile: dest=/etc/exports line="/opt/stage/root {{net}}/24(ro,sync,no_root_squash,no_subtree_check,fsid=2)" state=absent

    - name: Add in read-write nfs rule
      lineinfile: dest=/etc/exports line="/opt/stage/root {{net}}/24(rw,sync,no_root_squash,no_subtree_check,fsid=2)" state=present

    - include: start_serving_image.yml
      vars:
        nfs_mount_point: /opt/stage
        image: /opt/rpi_img/stage.img