# This playbook is used to move an image from staging to prod or vice-versa.

- hosts: 127.0.0.1
  connection: local
  remote_user: chrome-bot
  become_user: root
  become: yes
  become_method: sudo
  vars:
    from: stage
    to: prod

  tasks:
    - include: stop_serving_image.yml
      vars:
        nfs_mount_point: /opt/{{to}}

    - copy: src=/opt/rpi_img/{{from}}.img dest=/opt/rpi_img/{{to}}.img owner=chrome-bot group=chrome-bot mode=0644

    - include: start_serving_image.yml
      vars:
        nfs_mount_point: /opt/{{to}}
        image: /opt/rpi_img/{{to}}.img