# Still need .boto.
- name: Copy empty .boto file.
  copy:
    src: files/.boto
    dest: ~chrome-bot/.boto
    owner: chrome-bot
    group: chrome-bot
    mode: 0644

- name: Install mobile device applications.
  become: yes
  apt:
    pkg:
      - adb
      - libimobiledevice-utils
  when: swarming_needs__needs_mobile_tools

- name: Install python3 modules.
  become: yes
  apt:
    pkg:
      - python3-distutils
      - python3-certifi

# Our recipes hard code a specific adb.
- name: link adb to /usr/bin/adb.1.0.35
  become: yes
  file:
    src: /usr/bin/adb
    dest: /usr/bin/adb.1.0.35
    owner: root
    group: root
    state: link
  when: swarming_needs__needs_mobile_tools

# Recipes need a /usr/bin/python.
- name: link /usr/bin/python to /usr/bin/python3
  become: yes
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    owner: root
    group: root
    state: link

- name: Create /b/s directory
  become: yes
  file:
    path: /b/s
    state: directory
    recurse: yes
    owner: chrome-bot
    mode: 0755

- name: Create /etc/swarming_config directory
  become: yes
  file:
    path: /etc/swarming_config
    state: directory
    recurse: yes
    owner: chrome-bot
    mode: 0755

- name: Copy oauth2 config file
  become: yes
  template:
    src: templates/oauth2_access_token_config.json
    dest: /etc/swarming_config/oauth2_access_token_config.json
    owner: chrome-bot
    mode: 0644
