- name: Install mobile device applications.
  become: yes
  apt:
    pkg:
      - adb
      - libimobiledevice-utils
  when: swarming_needs__needs_mobile_tools

- name: Install python3 modules.
  become: yes
  apt:
    pkg:
      - python3-distutils
      - python3-certifi

# Our recipes hard code a specific adb.
- name: link adb to /usr/bin/adb.1.0.35
  become: yes
  file:
    src: /usr/bin/adb
    dest: /usr/bin/adb.1.0.35
    owner: root
    group: root
    state: link
  when: swarming_needs__needs_mobile_tools

# Recipes need a /usr/bin/python.
- name: link /usr/bin/python to /usr/bin/python3
  become: yes
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    owner: root
    group: root
    state: link

- name: Create /b/s directory
  become: yes
  file:
    path: /b/s
    state: directory
    recurse: yes
    owner: chrome-bot
    mode: 0755

