- name: Install mobile tools.
  when: swarming_needs__needs_mobile_tools
  block:
    - name: Load skia-imobiledevice package.
      import_role:
        name: get_ansible_binaries
      vars:
        get_ansible_binaries_application: imobiledevice

    - name: Make temp dir to hold skia-imobiledevice package.
      tempfile:
        state: directory
      register: package_dir
      notify: clean_up_package_dir

    - name: Copy package to host.
      become: yes
      copy:
        src:
          "{{ get_ansible_binaries_directory.path }}/build/{{
      ansible_facts['system'] }}/{{ ansible_facts['architecture']
      }}/skia-imobiledevice.deb"
        dest: '{{ package_dir.path }}/skia-imobiledevice.deb'
        owner: root
        group: root
        mode: '0755'

    # Ansible's apt module doesn't want to remove conflicting packages, no
    # matter what options I could come up with, so we do it manually.
    - name: Remove packages that conflict with skia-imobiledevice.
      become: yes
      apt:
        state: absent
        pkg:
          - libplist3
          - libusbmuxd6
          - usbmuxd
          - ideviceinstaller
          - ifuse
          - libimobiledevice6
        autoremove: yes

    - name: Install skia-imobiledevice.
      become: yes
      apt:
        deb: '{{ package_dir.path }}/skia-imobiledevice.deb'

    - name: Install adb and python 2.7.
      become: yes
      apt:
        pkg:
          - adb
          - python2.7  # still needed for iOS swarming recipes

    # iOS recipes need a /usr/bin/python2.
    - name: link /usr/bin/python2 to /usr/bin/python2.7
      become: yes
      file:
        src: /usr/bin/python2.7
        dest: /usr/bin/python2
        owner: root
        group: root
        state: link

    # Our recipes hard-code a specific adb.
    - name: link adb to /usr/bin/adb.1.0.35
      become: yes
      file:
        src: /usr/bin/adb
        dest: /usr/bin/adb.1.0.35
        owner: root
        group: root
        state: link

- name: Install python3 modules.
  become: yes
  apt:
    pkg:
      - python3-distutils
      - python3-certifi

# Recipes need a /usr/bin/python.
- name: link /usr/bin/python to /usr/bin/python3
  become: yes
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    owner: root
    group: root
    state: link

- name: Create /b/s directory
  become: yes
  file:
    path: /b/s
    state: directory
    recurse: yes
    owner: chrome-bot
    mode: 0755

- name: Look for /etc/gdm3
  stat:
    path: /etc/gdm3
  register: gdm3_config_directory

- name: Copy gdm3 config to host, which causes chrome-bot to be automatically logged in for Debian 11 systems running Gnome.
  become: yes
  when: gdm3_config_directory.stat.exists
  copy:
    src: files/gdm3_daemon.conf
    dest: /etc/gdm3/daemon.conf
    owner: root
    group: root
    mode: '0644'

- name: Install build tools.
  when: swarming_needs__can_build
  become: yes
  apt:
    pkg:
      - make
      - fontconfig
      - libfontconfig-dev
      - libglu-dev

