- name: Fail if platform unsupported.
  fail:
    msg: This system isn't supported, please add support.
  when: ansible_facts['system']|lower not in ['linux', 'darwin', 'win32nt']

- name: Copy empty .boto file.
  copy:
    src: files/.boto
    dest: ~chrome-bot/.boto
    owner: 'chrome-bot'
    group: '{{ skolo_group }}'
    mode: 0644
  when: ansible_facts['system']|lower != "win32nt"

- name: Install Swarming prereqs for Linux.
  import_tasks: linux.yml
  when: ansible_facts['system']|lower == "linux"

- name: Install Swarming prereqs for Mac.
  import_tasks: mac.yml
  when: ansible_facts['system']|lower == "darwin"

- name: Install Swarming prereqs for Windows.
  import_tasks: win.yml
  when: ansible_facts['system']|lower == "win32nt"
