// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewPeerFinder creates a new instance of PeerFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPeerFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *PeerFinder {
	mock := &PeerFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PeerFinder is an autogenerated mock type for the PeerFinder type
type PeerFinder struct {
	mock.Mock
}

type PeerFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *PeerFinder) EXPECT() *PeerFinder_Expecter {
	return &PeerFinder_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type PeerFinder
func (_mock *PeerFinder) Start(ctx context.Context) ([]string, <-chan []string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 []string
	var r1 <-chan []string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, <-chan []string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) <-chan []string); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan []string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PeerFinder_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type PeerFinder_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PeerFinder_Expecter) Start(ctx interface{}) *PeerFinder_Start_Call {
	return &PeerFinder_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *PeerFinder_Start_Call) Run(run func(ctx context.Context)) *PeerFinder_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PeerFinder_Start_Call) Return(strings []string, stringsCh <-chan []string, err error) *PeerFinder_Start_Call {
	_c.Call.Return(strings, stringsCh, err)
	return _c
}

func (_c *PeerFinder_Start_Call) RunAndReturn(run func(ctx context.Context) ([]string, <-chan []string, error)) *PeerFinder_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewServer creates a new instance of Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Server {
	mock := &Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

type Server_Expecter struct {
	mock *mock.Mock
}

func (_m *Server) EXPECT() *Server_Expecter {
	return &Server_Expecter{mock: &_m.Mock}
}

// ClientConnectionHandler provides a mock function for the type Server
func (_mock *Server) ClientConnectionHandler(ctx context.Context) http.HandlerFunc {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClientConnectionHandler")
	}

	var r0 http.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func(context.Context) http.HandlerFunc); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}
	return r0
}

// Server_ClientConnectionHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientConnectionHandler'
type Server_ClientConnectionHandler_Call struct {
	*mock.Call
}

// ClientConnectionHandler is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Server_Expecter) ClientConnectionHandler(ctx interface{}) *Server_ClientConnectionHandler_Call {
	return &Server_ClientConnectionHandler_Call{Call: _e.mock.On("ClientConnectionHandler", ctx)}
}

func (_c *Server_ClientConnectionHandler_Call) Run(run func(ctx context.Context)) *Server_ClientConnectionHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Server_ClientConnectionHandler_Call) Return(handlerFunc http.HandlerFunc) *Server_ClientConnectionHandler_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *Server_ClientConnectionHandler_Call) RunAndReturn(run func(ctx context.Context) http.HandlerFunc) *Server_ClientConnectionHandler_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type Server
func (_mock *Server) Send(ctx context.Context, stream string, msg string) error {
	ret := _mock.Called(ctx, stream, msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, stream, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Server_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Server_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - stream string
//   - msg string
func (_e *Server_Expecter) Send(ctx interface{}, stream interface{}, msg interface{}) *Server_Send_Call {
	return &Server_Send_Call{Call: _e.mock.On("Send", ctx, stream, msg)}
}

func (_c *Server_Send_Call) Run(run func(ctx context.Context, stream string, msg string)) *Server_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Server_Send_Call) Return(err error) *Server_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Server_Send_Call) RunAndReturn(run func(ctx context.Context, stream string, msg string) error) *Server_Send_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type Server
func (_mock *Server) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Server_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Server_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Server_Expecter) Start(ctx interface{}) *Server_Start_Call {
	return &Server_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *Server_Start_Call) Run(run func(ctx context.Context)) *Server_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Server_Start_Call) Return(err error) *Server_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Server_Start_Call) RunAndReturn(run func(ctx context.Context) error) *Server_Start_Call {
	_c.Call.Return(run)
	return _c
}
