---
argument_specs:
  main:
    short_description:
      Arguments that can be passed to the copy_service_account_key role.
    options:
      service_account_name:
        type: 'string'
        required: true
        description:
          'The name of the secret in berglas etc that contains the service
          account key to use.'
