#!/usr/bin/env bash
set -e
set -x
set -o pipefail 

GITHUB_SHA="$1"
PULL_NUMBER="$2"

if [[ "$PULL_NUMBER" == "" ]]; then
  GITHUB_REF_NAME="main"
else
  GITHUB_REF_NAME=""
fi

# Create working directory for goldctl.
WORKDIR=/tmp/goldctl
mkdir -p "$WORKDIR"

# Clean up the working directory on exit.
cleanUpWorkDir() {
  rm -rf $WORKDIR
}

trap 'cleanUpWorkDir' EXIT


# Create directory to extract images to.
EXTRACT_DIR=/tmp/gold
mkdir -p "$EXTRACT_DIR"

bazelisk run //gold-client/cmd/goldctl -- auth --service-account /etc/gcs/service-account.json --work-dir $WORKDIR`

# bazelisk run //gold-client/cmd/goldctl -- auth --service-account ~/Downloads/api-project-146332866891-3816d0d33259.json --work-dir $WORKDIR`

# GITHUB_REF_NAME looks like either main or 1/merge for a pull request.
# Determine if we are running in a tryjob context by using that variable.
if [[ "$GITHUB_REF_NAME" == "main" ]]; then

  # Initialize goldctl with the appropriate parameters.
  bazelisk run //gold-client/cmd/goldctl -- imgtest init \
    --bucket goldmine-build-private \
    --git_hash $GITHUB_SHA \
    --work-dir $WORKDIR \
    --upload-only \
    --corpus goldmine \
    --instance goldmine \
    --key browser:chrome \
    --key os:`uname -o` \
    --key machine:`uname -m`

else
  printf "Running in tryjob context.\n"

  # GitHub does not have patchset numbers, so we use the commit hash of the
  # commit being tested as the patchset ID. BUT, GitHub does a merge commit for
  # PRs, so we need to get the first parent of that merge commit to get the
  # actual commit that is being tested. So we use git log to get the parents of
  # the commit, and then use sed to extract the second parent (the actual commit
  # being tested).
  COMMIT_HASH=$(git log --pretty=%P -n 1 $GITHUB_SHA | sed 's#.* ##')

  printf "PULL_NUMBER: %s\n" "$PULL_NUMBER"
  printf "COMMIT_HASH: %s\n" "$COMMIT_HASH"

  # Initialize goldctl with the appropriate parameters.
  bazelisk run //gold-client/cmd/goldctl -- imgtest init \
    --bucket goldmine-build-private \
    --git_hash $COMMIT_HASH \
    --work-dir $WORKDIR \
    --upload-only \
    --corpus goldmine \
    --instance goldmine \
    --key browser:chrome \
    --key os:`uname -o` \
    --key machine:`uname -m` \
    --crs=github \
    --cis=github \
    --changelist $PULL_NUMBER \
    --patchset_id $COMMIT_HASH \
    --jobid $PULL_NUMBER-$COMMIT_HASH # The GitHub lookupSystem can parse this and map the COMMIT_HASH to a patch number.

fi


# Extract the screenshots generated by the tests to the "EXTRACT_DIR" directory.
bazelisk run //puppeteer-tests/bazel/extract_puppeteer_screenshots -- --output_dir=$EXTRACT_DIR

# Loop over all files in the "EXTRACT_DIR" directory and `imgtest add` them,
# which uploads the individual images to the cloud storage bucket, and also
# updates the local metadata in the WORKDIR.
for filename in $EXTRACT_DIR/*.png; do
  bazelisk run //gold-client/cmd/goldctl -- imgtest add --png-file $filename --test-name `echo $(basename $filename) | sed s/.png//` --work-dir $WORKDIR
done

# Finalize the upload by uploading the metadata in the WORKDIR to the cloud
# storage bucket.
bazelisk run //gold-client/cmd/goldctl -- imgtest finalize --work-dir $WORKDIR
