#!/usr/bin/env bash
set -e
set -x
set -o pipefail 

# Create working directory for goldctl.
WORKDIR=/tmp/goldctl
mkdir -p "$WORKDIR"

# Create directory to extract images to.
EXTRACT_DIR=/tmp/gold
mkdir -p "$EXTRACT_DIR"


echo "$GCP_GCS_SERVICE_ACCT" > /tmp/serice-account.json

bazel run //gold-client/cmd/goldctl -- auth --service-account /tmp/serice-account.json --work-dir $WORKDIR`

# bazel run //gold-client/cmd/goldctl -- auth --service-account ~/Downloads/api-project-146332866891-3816d0d33259.json --work-dir $WORKDIR`

# Run all the modules tests which generate images to be uploaded to Gold.
bazel test //golden/modules/... //perf/modules/...

# Initialize goldctl with the appropriate parameters.
bazel run //gold-client/cmd/goldctl -- imgtest init \
  --bucket goldmine-build-private \
  --git_hash `git rev-parse HEAD` \
  --work-dir $WORKDIR \
  --upload-only \
  --corpus goldmine \
  --instance goldmine \
  --key browser:chrome \
  --key os:`uname -o` \
  --key machine:`uname -m`

# Extract the screenshots generated by the tests to the "EXTRACT_DIR" directory.
bazel run //puppeteer-tests/bazel/extract_puppeteer_screenshots -- --output_dir=$EXTRACT_DIR

# Loop over all files in the "EXTRACT_DIR" directory and `imgtest add` them,
# which uploads the individual images to the cloud storage bucket, and also
# updates the local metadata in the WORKDIR.
for filename in $EXTRACT_DIR/*.png; do
  bazel run //gold-client/cmd/goldctl -- imgtest add --png-file $filename --test-name `echo $(basename $filename) | sed s/.png//` --work-dir $WORKDIR
done

# Finalize the upload by uploading the metadata in the WORKDIR to the cloud
# storage bucket.
bazel run //gold-client/cmd/goldctl -- imgtest finalize --work-dir $WORKDIR
