#!/usr/bin/env bash
set -e
set -x
set -o pipefail 

# Create working directory for goldctl.
WORKDIR=/tmp/goldctl
mkdir -p "$WORKDIR"

# Create directory to extract images to.
EXTRACT_DIR=/tmp/gold
mkdir -p "$EXTRACT_DIR"


echo "$GCP_GCS_SERVICE_ACCT" > /tmp/serice-account.json

bazel run //gold-client/cmd/goldctl -- auth --service-account /tmp/serice-account.json --work-dir $WORKDIR`

# bazel run //gold-client/cmd/goldctl -- auth --service-account ~/Downloads/api-project-146332866891-3816d0d33259.json --work-dir $WORKDIR`

# Run all the modules tests which generate images to be uploaded to Gold.
bazel test //golden/modules/... //perf/modules/...

# GITHUB_REF_NAME looks like either main or 1/merge for a pull request.
# Determine if we are running in a tryjob context by using that variable.
if [[ "$GITHUB_REF_NAME" == "main" ]]; then

# Initialize goldctl with the appropriate parameters.
bazel run //gold-client/cmd/goldctl -- imgtest init \
  --bucket goldmine-build-private \
  --git_hash `git rev-parse HEAD` \
  --work-dir $WORKDIR \
  --upload-only \
  --corpus goldmine \
  --instance goldmine \
  --key browser:chrome \
  --key os:`uname -o` \
  --key machine:`uname -m`

else
  printf "Running in tryjob context.\n"

  # Slice the '1' off of '1/merge'.
  PULL_NUMBER=$(echo $GITHUB_REF_NAME | cut -d'/' -f1) 

  # GitHub does not have patchset numbers, so we use the commit hash of the
  # commit being tested as the patchset ID. BUT, GitHub does a merge commit for
  # PRs, so we need to get the first parent of that merge commit to get the
  # actual commit that is being tested. So we use git log to get the parents of
  # the commit, and then use sed to extract the second parent (the actual commit
  # being tested).
  COMMIT_HASH=$(git log --pretty=%P -n 1 $GITHUB_SHA | sed 's#.* ##')

  printf "PULL_NUMBER: %s\n" "$PULL_NUMBER"
  printf "COMMIT_HASH: %s\n" "$COMMIT_HASH"

# Initialize goldctl with the appropriate parameters.
bazel run //gold-client/cmd/goldctl -- imgtest init \
  --bucket goldmine-build-private \
  --git_hash $COMMIT_HASH \
  --work-dir $WORKDIR \
  --upload-only \
  --corpus goldmine \
  --instance goldmine \
  --key browser:chrome \
  --key os:`uname -o` \
  --key machine:`uname -m` \
  --crs=github \
	--cis=github \
  --changelist $PULL_NUMBER \
  --patchset 0 \  # Using 0 here to indicate we are using patchset_id
  --patchset_id $COMMIT_HASH
  --jobid $PULL_NUMBER-$COMMIT_HASH # The GitHub lookupSystem can parse this and map the COMMIT_HASH to a patch number.

fi


# Extract the screenshots generated by the tests to the "EXTRACT_DIR" directory.
bazel run //puppeteer-tests/bazel/extract_puppeteer_screenshots -- --output_dir=$EXTRACT_DIR

# Loop over all files in the "EXTRACT_DIR" directory and `imgtest add` them,
# which uploads the individual images to the cloud storage bucket, and also
# updates the local metadata in the WORKDIR.
for filename in $EXTRACT_DIR/*.png; do
  bazel run //gold-client/cmd/goldctl -- imgtest add --png-file $filename --test-name `echo $(basename $filename) | sed s/.png//` --work-dir $WORKDIR
done

# Finalize the upload by uploading the metadata in the WORKDIR to the cloud
# storage bucket.
bazel run //gold-client/cmd/goldctl -- imgtest finalize --work-dir $WORKDIR
