---
# Ensure Python 2.7.
- hosts: all
  remote_user: chrome-bot
  become: yes
  vars:
    pkg_filename: python-2.7.14-macosx10.6.pkg

  tasks:
    - name: Install Rosetta 2
      command: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    - name: Download Python package
      get_url:
        url: https://www.python.org/ftp/python/2.7.14/{{ pkg_filename }}
        dest: "{{ home }}/Downloads"
    - name: Install Python package
      command: /usr/sbin/installer -verboseR -package {{ home }}/Downloads/{{ pkg_filename }}
        -target /
