apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-{{.INSTANCE_ID}}-crashing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gold-{{.INSTANCE_ID}}-crashing-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gold-{{.INSTANCE_ID}}-crashing-server
        appgroup: gold-{{.INSTANCE_ID}}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 2000 # aka skia
        fsGroup: 2000   # aka skia
      containers:
        - name: gold-{{.INSTANCE_ID}}-crashing-server
          image: {{.CRASHING_SERVER_IMAGE}}
          args:
            - "--instance={{.INSTANCE_ID}}"
            - "--port=8000"
            - "--crash_after_seconds=5"
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              memory: "{{.MAIN_MEMORY}}"
              cpu: "{{.MAIN_CPU}}"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 1
            periodSeconds: 1
            failureThreshold: 3
