apiVersion: v1
kind: Service
metadata:
  name: gold-{{.INSTANCE_ID}}-ingestion-bt
spec:
  ports:
    - name: http
      port: 9091
    - name: metrics
      port: 20000
  selector:
      app: gold-{{.INSTANCE_ID}}-ingestion-bt
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-{{.INSTANCE_ID}}-ingestion-bt
spec:
  replicas: 1 # Start with one so you don't make duplicate GCS Pubsub subscriptions
  selector:
    matchLabels:
      app: gold-{{.INSTANCE_ID}}-ingestion-bt
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gold-{{.INSTANCE_ID}}-ingestion-bt  # Pod template's label selector
        appgroup: gold-{{.INSTANCE_ID}}
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "20000"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 2000 # aka skia
        fsGroup: 2000   # aka skia
      containers:
        - name: gold-{{.INSTANCE_ID}}-ingestion-bt
          image: {{.INGESTION_BT_IMAGE}}
          args:
            - "--bt_instance={{.BIGTABLE_INSTANCE}}"
            - "--bt_project_id={{.BIGTABLE_PROJECT}}"
            - "--config_filename=/etc/gold-ingestion/gold-{{.INSTANCE_ID}}-ingestion-config-bt.json5"
            - "--fs_namespace={{.INSTANCE_ID}}"
            - "--fs_project_id={{.FIRESTORE_PROJECT}}"
            - "--git_bt_table={{.GIT_BT_TABLE}}"
            - "--http_port=:9091"
            - "--logtostderr"
            - "--prom_port=:20000"
            - "--pubsub_project_id={{.PUBSUB_PROJECT}}"
          ports:
            - containerPort: 9091
              name: http-health
          volumeMounts:
            - name: gold-{{.INSTANCE_ID}}-ingestion-config-volume
              mountPath: /etc/gold-ingestion
            - name: gold-service-account-secrets
              mountPath: /var/secrets/google
            {{if eq .CODE_REVIEW_SYSTEM "github"}}
            - name: gold-github-token
              mountPath: /var/secrets/github/
            {{end}}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/service-account.json
          resources:
            requests:
              memory: "12Gi"
              cpu: 6
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9091
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: gold-{{.INSTANCE_ID}}-ingestion-config-volume
          configMap:
            defaultMode: 420
            name: gold-{{.INSTANCE_ID}}-ingestion-config-bt
        - name: gold-service-account-secrets
          secret:
            secretName: gold-service-account-secrets
        {{if eq .CODE_REVIEW_SYSTEM "github"}}
        - name: gold-github-token
          secret:
            secretName: gold-github-token
        {{end}}
