- name: Copy authorized_keys to Darwin
  copy:
    src: '{{ role_path }}/../../../../authorized_keys'
    dest: '/Users/{{ skolo_account }}/.ssh/authorized_keys'
    owner: '{{ skolo_account }}'
    mode: 0644
