- name: Create .ssh directory if it doesn't exist.
  ansible.windows.win_file:
    path: "C:\\Users\\{{ skolo_account }}\\.ssh"
    state: directory

- name: Copy authorized_keys
  ansible.builtin.copy:
    src: '{{ all.repo_root }}/skolo/authorized_keys'
    dest: "C:\\Users\\{{ skolo_account }}\\.ssh\\authorized_keys"
  notify: win_restart_sshd
