- name: Load powercycle_server_ansible executables.
  import_role:
    name: get_ansible_binaries
  vars:
    get_ansible_binaries_application: powercycle_server_ansible
    get_ansible_binaries_version: '{{ powercycle_server_ansible_version }}'

- name: Copy over service file.
  become: yes
  template:
    src: templates/powercycle_server_ansible.service
    dest: /etc/systemd/system/powercycle_server_ansible.service
    owner: root
    group: root
    mode: '0644'

- name: Copy over executable.
  become: yes
  copy:
    src:
      "{{ get_ansible_binaries_directory.path }}/build/{{
      ansible_facts['system'] }}/{{ ansible_facts['architecture']
      }}/powercycle_server_ansible"
    dest: /usr/local/bin/powercycle_server_ansible
    owner: root
    group: root
    mode: '0755'

- name: Start systemd servce.
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: powercycle_server_ansible
    daemon_reload: yes
