// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io/fs"

	mock "github.com/stretchr/testify/mock"
	"go.goldmine.build/go/vfs"
)

// NewFS creates a new instance of FS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *FS {
	mock := &FS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FS is an autogenerated mock type for the FS type
type FS struct {
	mock.Mock
}

type FS_Expecter struct {
	mock *mock.Mock
}

func (_m *FS) EXPECT() *FS_Expecter {
	return &FS_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type FS
func (_mock *FS) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FS_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type FS_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FS_Expecter) Close(ctx interface{}) *FS_Close_Call {
	return &FS_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *FS_Close_Call) Run(run func(ctx context.Context)) *FS_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FS_Close_Call) Return(err error) *FS_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FS_Close_Call) RunAndReturn(run func(ctx context.Context) error) *FS_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type FS
func (_mock *FS) Create(ctx context.Context, name string) (vfs.File, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 vfs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (vfs.File, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) vfs.File); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vfs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FS_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FS_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *FS_Expecter) Create(ctx interface{}, name interface{}) *FS_Create_Call {
	return &FS_Create_Call{Call: _e.mock.On("Create", ctx, name)}
}

func (_c *FS_Create_Call) Run(run func(ctx context.Context, name string)) *FS_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FS_Create_Call) Return(file vfs.File, err error) *FS_Create_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *FS_Create_Call) RunAndReturn(run func(ctx context.Context, name string) (vfs.File, error)) *FS_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type FS
func (_mock *FS) Open(ctx context.Context, name string) (vfs.File, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 vfs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (vfs.File, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) vfs.File); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vfs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type FS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *FS_Expecter) Open(ctx interface{}, name interface{}) *FS_Open_Call {
	return &FS_Open_Call{Call: _e.mock.On("Open", ctx, name)}
}

func (_c *FS_Open_Call) Run(run func(ctx context.Context, name string)) *FS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FS_Open_Call) Return(file vfs.File, err error) *FS_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *FS_Open_Call) RunAndReturn(run func(ctx context.Context, name string) (vfs.File, error)) *FS_Open_Call {
	_c.Call.Return(run)
	return _c
}

// NewFile creates a new instance of File. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *File {
	mock := &File{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// File is an autogenerated mock type for the File type
type File struct {
	mock.Mock
}

type File_Expecter struct {
	mock *mock.Mock
}

func (_m *File) EXPECT() *File_Expecter {
	return &File_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type File
func (_mock *File) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// File_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type File_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *File_Expecter) Close(ctx interface{}) *File_Close_Call {
	return &File_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *File_Close_Call) Run(run func(ctx context.Context)) *File_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *File_Close_Call) Return(err error) *File_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *File_Close_Call) RunAndReturn(run func(ctx context.Context) error) *File_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type File
func (_mock *File) Read(ctx context.Context, buf []byte) (int, error) {
	ret := _mock.Called(ctx, buf)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (int, error)); ok {
		return returnFunc(ctx, buf)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) int); ok {
		r0 = returnFunc(ctx, buf)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, buf)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type File_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - buf []byte
func (_e *File_Expecter) Read(ctx interface{}, buf interface{}) *File_Read_Call {
	return &File_Read_Call{Call: _e.mock.On("Read", ctx, buf)}
}

func (_c *File_Read_Call) Run(run func(ctx context.Context, buf []byte)) *File_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *File_Read_Call) Return(n int, err error) *File_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *File_Read_Call) RunAndReturn(run func(ctx context.Context, buf []byte) (int, error)) *File_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function for the type File
func (_mock *File) ReadDir(ctx context.Context, n int) ([]fs.FileInfo, error) {
	ret := _mock.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]fs.FileInfo, error)); ok {
		return returnFunc(ctx, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []fs.FileInfo); ok {
		r0 = returnFunc(ctx, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type File_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - ctx context.Context
//   - n int
func (_e *File_Expecter) ReadDir(ctx interface{}, n interface{}) *File_ReadDir_Call {
	return &File_ReadDir_Call{Call: _e.mock.On("ReadDir", ctx, n)}
}

func (_c *File_ReadDir_Call) Run(run func(ctx context.Context, n int)) *File_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *File_ReadDir_Call) Return(fileInfos []fs.FileInfo, err error) *File_ReadDir_Call {
	_c.Call.Return(fileInfos, err)
	return _c
}

func (_c *File_ReadDir_Call) RunAndReturn(run func(ctx context.Context, n int) ([]fs.FileInfo, error)) *File_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type File
func (_mock *File) Stat(ctx context.Context) (fs.FileInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (fs.FileInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) fs.FileInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type File_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
func (_e *File_Expecter) Stat(ctx interface{}) *File_Stat_Call {
	return &File_Stat_Call{Call: _e.mock.On("Stat", ctx)}
}

func (_c *File_Stat_Call) Run(run func(ctx context.Context)) *File_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *File_Stat_Call) Return(fileInfo fs.FileInfo, err error) *File_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *File_Stat_Call) RunAndReturn(run func(ctx context.Context) (fs.FileInfo, error)) *File_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type File
func (_mock *File) Write(ctx context.Context, b []byte) (int, error) {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (int, error)); ok {
		return returnFunc(ctx, b)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) int); ok {
		r0 = returnFunc(ctx, b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type File_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - b []byte
func (_e *File_Expecter) Write(ctx interface{}, b interface{}) *File_Write_Call {
	return &File_Write_Call{Call: _e.mock.On("Write", ctx, b)}
}

func (_c *File_Write_Call) Run(run func(ctx context.Context, b []byte)) *File_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *File_Write_Call) Return(n int, err error) *File_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *File_Write_Call) RunAndReturn(run func(ctx context.Context, b []byte) (int, error)) *File_Write_Call {
	_c.Call.Return(run)
	return _c
}
