# Alerts for things in the skia-public cluster only.
#
# If anything in this file starts to run in another cluster, such as
# skia-corp, then break it out into its own alerts_NNNN.yml file
# and include it in each prometheus-CLUSTER.yml file that is it running in.
groups:
  - name: general
    rules:

      - alert: FlutterLicenseScriptFailure
        expr:
          flutter_license_script_failure{app="autoroll-be-skia-flutter-autoroll"}
          > 0
        for: 5m
        labels:
          category: infra
          severity: critical
          owner: rmistry@google.com
        annotations:
          description:
            'The License scripts in the Skia->Flutter roller have failed.
            https://console.cloud.google.com/logs/viewer?project={{
            $labels.project }}&resource=k8s_container%2Fcluster_name%2F{{
            $labels.cluster }}%2Fnamespace_name%2Fdefault%2Fcontainer_name%2F{{
            $labels.app }}
            https://skia.googlesource.com/buildbot/%2B/main/autoroll/PROD.md#flutter_license_script_failure'

      # skia-flutter-autoroll takes a long time to transition because its pre-upload
      # scripts run flutter's license script which can take around 40 minutes.
      - alert: AutoRollLastTransition
        expr:
          liveness_last_successful_autoroll_tick_s{roller="skia-flutter-autoroll"}
          > 50*60
        labels:
          category: infra
          severity: critical
          owner: rmistry@google.com
        annotations:
          abbr: 'skia-flutter-autoroll'
          description:
            'Autoroll on {{ $labels.app }} has failed to transition for more
            than 50 minutes.
            https://console.cloud.google.com/logs/viewer?project={{
            $labels.project }}&resource=k8s_container%2Fcluster_name%2F{{
            $labels.cluster }}%2Fnamespace_name%2Fdefault%2Fcontainer_name%2F{{
            $labels.app }}'


