# Alerts for things in the skia-corp cluster only.
groups:
- name: general
  rules:
  - alert: InternalAutoRoll
    expr: autoroll_last_roll_result{roller="skia-internal-autoroll"} == 0
    for: 10m
    labels:
      category: infra
      severity: warning
      owner: borenet@google.com
    annotations:
      description: 'The last DEPS roll into internal_test repo failed. https://skia.googlesource.com/buildbot/%2B/master/autoroll/PROD.md#autoroll_failed'

  - alert: InternalAutoRoll24H
    expr: liveness_last_autoroll_landed_s{roller="skia-internal-autoroll"}/60/60 > 24
    labels:
      category: infra
      severity: warning
      owner: borenet@google.com
    annotations:
      description: 'The last-landed roll into internal_test was over 24h ago. https://skia.googlesource.com/buildbot/%2B/master/autoroll/PROD.md#no_rolls_24h'

# Android Compile Server
  - alert: AndroidCompileTooManyWaitingTasks
    expr: android_compile_waiting_tasks{app="android-compile"} >= 5
    for: 5m
    labels:
      category: infra
      severity: warning
      owner: rmistry@google.com
    annotations:
      description: 'There are 5 or more waiting android compile tasks. https://skia.googlesource.com/buildbot/%2B/master/android_compile/PROD.md#queue_too_long'

  - alert: AndroidCompileMirrorSyncFailed
    expr: android_compile_mirror_sync_failure{app="android-compile"} > 0
    for: 5m
    labels:
      category: infra
      severity: warning
      owner: rmistry@google.com
    annotations:
      description: 'Mirror sync in android compile server failed. https://skia.googlesource.com/buildbot/%2B/master/android_compile/PROD.md#mirror_sync_failed'

  - alert: AndroidCompileTreeBroken
    expr: android_compile_tree_broken{app="android-compile"} > 0
    for: 5m
    labels:
      category: infra
      severity: warning
      owner: rmistry@google.com
    annotations:
      description: 'Android tree might be broken. Both withpatch and nopatch runs failed on android compile server. https://skia.googlesource.com/buildbot/%2B/master/android_compile/PROD.md#android_tree_broken'
