scrape_configs:
  - job_name: 'pulld-not-gce'
    static_configs:
      - targets: ['localhost:20000']

  - job_name: 'file-backup'
    static_configs:
      - targets: ['localhost:20002']
        labels:
          backup: router_config

  # Prometheus self monitoring.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:8000']


