global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:8080

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'iap-proxy'
    static_configs:
      - targets: ['localhost:10000']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9090']
  - job_name: 'alertmanager-iap-proxy'
    static_configs:
      - targets: ['alertmanager:10000']
