apiVersion: v1
kind: Service
metadata:
  labels:
    app: proberk
  name: proberk
spec:
  ports:
    - name: metrics
      port: 20000
  selector:
    app: proberk
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: proberk
spec:
  template:
    metadata:
      labels:
        app: proberk
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 2000 # aka skia
        fsGroup: 2000   # aka skia
      containers:
        - name: proberk
          image: gcr.io/skia-public/proberk:2018-05-14T18_12_39Z-jcgregorio-b601ac5-dirty
          args:
            - "--logtostderr"
            - "--config=/etc/proberk/allprobersk.json"
            - "--prom_port=:20000"
          ports:
            - name: metrics
              containerPort: 20000
          volumeMounts:
            - name: config-volume
              mountPath: /etc/proberk
          resources:
            requests:
              memory: "100Mi"
              cpu: "25m"
      volumes:
        - name: config-volume
          configMap:
            name: proberk-conf
