// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.goldmine.build/go/git/provider"
)

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

// CommitsFromMostRecentGitHashToHead provides a mock function for the type Provider
func (_mock *Provider) CommitsFromMostRecentGitHashToHead(ctx context.Context, mostRecentGitHash string, cb provider.CommitProcessor) error {
	ret := _mock.Called(ctx, mostRecentGitHash, cb)

	if len(ret) == 0 {
		panic("no return value specified for CommitsFromMostRecentGitHashToHead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, provider.CommitProcessor) error); ok {
		r0 = returnFunc(ctx, mostRecentGitHash, cb)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Provider_CommitsFromMostRecentGitHashToHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitsFromMostRecentGitHashToHead'
type Provider_CommitsFromMostRecentGitHashToHead_Call struct {
	*mock.Call
}

// CommitsFromMostRecentGitHashToHead is a helper method to define mock.On call
//   - ctx context.Context
//   - mostRecentGitHash string
//   - cb provider.CommitProcessor
func (_e *Provider_Expecter) CommitsFromMostRecentGitHashToHead(ctx interface{}, mostRecentGitHash interface{}, cb interface{}) *Provider_CommitsFromMostRecentGitHashToHead_Call {
	return &Provider_CommitsFromMostRecentGitHashToHead_Call{Call: _e.mock.On("CommitsFromMostRecentGitHashToHead", ctx, mostRecentGitHash, cb)}
}

func (_c *Provider_CommitsFromMostRecentGitHashToHead_Call) Run(run func(ctx context.Context, mostRecentGitHash string, cb provider.CommitProcessor)) *Provider_CommitsFromMostRecentGitHashToHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 provider.CommitProcessor
		if args[2] != nil {
			arg2 = args[2].(provider.CommitProcessor)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Provider_CommitsFromMostRecentGitHashToHead_Call) Return(err error) *Provider_CommitsFromMostRecentGitHashToHead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Provider_CommitsFromMostRecentGitHashToHead_Call) RunAndReturn(run func(ctx context.Context, mostRecentGitHash string, cb provider.CommitProcessor) error) *Provider_CommitsFromMostRecentGitHashToHead_Call {
	_c.Call.Return(run)
	return _c
}

// GitHashesInRangeForFile provides a mock function for the type Provider
func (_mock *Provider) GitHashesInRangeForFile(ctx context.Context, begin string, end string, filename string) ([]string, error) {
	ret := _mock.Called(ctx, begin, end, filename)

	if len(ret) == 0 {
		panic("no return value specified for GitHashesInRangeForFile")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]string, error)); ok {
		return returnFunc(ctx, begin, end, filename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []string); ok {
		r0 = returnFunc(ctx, begin, end, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, begin, end, filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Provider_GitHashesInRangeForFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GitHashesInRangeForFile'
type Provider_GitHashesInRangeForFile_Call struct {
	*mock.Call
}

// GitHashesInRangeForFile is a helper method to define mock.On call
//   - ctx context.Context
//   - begin string
//   - end string
//   - filename string
func (_e *Provider_Expecter) GitHashesInRangeForFile(ctx interface{}, begin interface{}, end interface{}, filename interface{}) *Provider_GitHashesInRangeForFile_Call {
	return &Provider_GitHashesInRangeForFile_Call{Call: _e.mock.On("GitHashesInRangeForFile", ctx, begin, end, filename)}
}

func (_c *Provider_GitHashesInRangeForFile_Call) Run(run func(ctx context.Context, begin string, end string, filename string)) *Provider_GitHashesInRangeForFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Provider_GitHashesInRangeForFile_Call) Return(strings []string, err error) *Provider_GitHashesInRangeForFile_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Provider_GitHashesInRangeForFile_Call) RunAndReturn(run func(ctx context.Context, begin string, end string, filename string) ([]string, error)) *Provider_GitHashesInRangeForFile_Call {
	_c.Call.Return(run)
	return _c
}

// LogEntry provides a mock function for the type Provider
func (_mock *Provider) LogEntry(ctx context.Context, gitHash string) (string, error) {
	ret := _mock.Called(ctx, gitHash)

	if len(ret) == 0 {
		panic("no return value specified for LogEntry")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, gitHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, gitHash)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, gitHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Provider_LogEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogEntry'
type Provider_LogEntry_Call struct {
	*mock.Call
}

// LogEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - gitHash string
func (_e *Provider_Expecter) LogEntry(ctx interface{}, gitHash interface{}) *Provider_LogEntry_Call {
	return &Provider_LogEntry_Call{Call: _e.mock.On("LogEntry", ctx, gitHash)}
}

func (_c *Provider_LogEntry_Call) Run(run func(ctx context.Context, gitHash string)) *Provider_LogEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Provider_LogEntry_Call) Return(s string, err error) *Provider_LogEntry_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Provider_LogEntry_Call) RunAndReturn(run func(ctx context.Context, gitHash string) (string, error)) *Provider_LogEntry_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Provider
func (_mock *Provider) Update(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Provider_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Provider_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Provider_Expecter) Update(ctx interface{}) *Provider_Update_Call {
	return &Provider_Update_Call{Call: _e.mock.On("Update", ctx)}
}

func (_c *Provider_Update_Call) Run(run func(ctx context.Context)) *Provider_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Provider_Update_Call) Return(err error) *Provider_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Provider_Update_Call) RunAndReturn(run func(ctx context.Context) error) *Provider_Update_Call {
	_c.Call.Return(run)
	return _c
}
