- name: Fail if platform unsupported.
  fail:
    msg: This platform is not yet supported.
  when: "ansible_facts['system']|lower not in ['darwin', 'linux']"

- name: Build test_machine_monitor for the target machine.
  delegate_to: 127.0.0.1
  make:
    chdir: '{{ all.repo_root }}/machine/'
    target:
      "build_test_machine_monitor_{{ ansible_facts['architecture'] }}_{{
      ansible_facts['system'] }}"

- name: Copy over executable.
  become: yes
  copy:
    src:
      "{{ all.repo_root }}/machine/build/{{ ansible_facts['system'] }}/{{
      ansible_facts['architecture'] }}/test_machine_monitor"
    dest: /usr/local/bin/test_machine_monitor
    owner: root
    group: "{{ (ansible_facts['system']|lower == 'darwin') | ternary('wheel', 'root') }}"
    mode: 0755

- name: Install startup job for Linux.
  import_tasks: linux.yml
  when: ansible_facts['system']|lower == 'linux'

- name: Install startup job for Mac.
  import_tasks: mac.yml
  when: ansible_facts['system']|lower == 'darwin'
