---
- name: Build test_machine_monitor for the target machine.
  delegate_to: 127.0.0.1
  make:
    chdir: '{{ all.repo_root }}/machine/'
    target:
      "build_test_machine_monitor_{{ ansible_facts['architecture'] }}_{{
      ansible_facts['system'] }}"

- name: Copy over service file.
  become: yes
  template:
    src: templates/test_machine_monitor.service
    dest: /etc/systemd/system/test_machine_monitor.service
    owner: root
    group: root
    mode: '0644'

- name: Copy over executable.
  become: yes
  copy:
    src:
      "{{ all.repo_root }}/machine/build/{{ ansible_facts['system'] }}/{{
      ansible_facts['architecture'] }}/test_machine_monitor"
    dest: /usr/local/bin/test_machine_monitor
    owner: root
    group: root
    mode: '0755'

- name: Start systemd servce.
  become: yes
  systemd:
    enabled: yes
    # Do not force a restart, we'll just pick up the new version on reboot.
    state: started
    name: test_machine_monitor
    daemon_reload: yes
