- name: Fail if platform unsupported.
  fail:
    msg: This platform is not yet supported.
  when: "ansible_facts['system']|lower not in ['darwin', 'linux', 'win32nt']"

- name: Build test_machine_monitor for the target machine.
  delegate_to: 127.0.0.1
  make:
    chdir: '{{ all.repo_root }}/machine/'
    target:
      "build_test_machine_monitor_{{ ansible_facts['architecture'] }}_{{
      ansible_facts['system'] }}"

- name: Install startup job for Linux.
  import_tasks: linux.yml
  when: ansible_facts['system']|lower == 'linux'

- name: Install startup job for Mac.
  import_tasks: mac.yml
  when: ansible_facts['system']|lower == 'darwin'

- name: Install startup job for Win.
  import_tasks: win.yml
  when: ansible_facts['system']|lower == 'win32nt'
