// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.goldmine.build/golden/go/types"
)

// NewImageSource creates a new instance of ImageSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageSource {
	mock := &ImageSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ImageSource is an autogenerated mock type for the ImageSource type
type ImageSource struct {
	mock.Mock
}

type ImageSource_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageSource) EXPECT() *ImageSource_Expecter {
	return &ImageSource_Expecter{mock: &_m.Mock}
}

// GetImage provides a mock function for the type ImageSource
func (_mock *ImageSource) GetImage(ctx context.Context, digest types.Digest) ([]byte, error) {
	ret := _mock.Called(ctx, digest)

	if len(ret) == 0 {
		panic("no return value specified for GetImage")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Digest) ([]byte, error)); ok {
		return returnFunc(ctx, digest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Digest) []byte); ok {
		r0 = returnFunc(ctx, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Digest) error); ok {
		r1 = returnFunc(ctx, digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ImageSource_GetImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImage'
type ImageSource_GetImage_Call struct {
	*mock.Call
}

// GetImage is a helper method to define mock.On call
//   - ctx context.Context
//   - digest types.Digest
func (_e *ImageSource_Expecter) GetImage(ctx interface{}, digest interface{}) *ImageSource_GetImage_Call {
	return &ImageSource_GetImage_Call{Call: _e.mock.On("GetImage", ctx, digest)}
}

func (_c *ImageSource_GetImage_Call) Run(run func(ctx context.Context, digest types.Digest)) *ImageSource_GetImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Digest
		if args[1] != nil {
			arg1 = args[1].(types.Digest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ImageSource_GetImage_Call) Return(bytes []byte, err error) *ImageSource_GetImage_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *ImageSource_GetImage_Call) RunAndReturn(run func(ctx context.Context, digest types.Digest) ([]byte, error)) *ImageSource_GetImage_Call {
	_c.Call.Return(run)
	return _c
}
