// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.goldmine.build/golden/go/continuous_integration"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetTryJob provides a mock function for the type Client
func (_mock *Client) GetTryJob(ctx context.Context, id string) (continuous_integration.TryJob, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTryJob")
	}

	var r0 continuous_integration.TryJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (continuous_integration.TryJob, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) continuous_integration.TryJob); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(continuous_integration.TryJob)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetTryJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTryJob'
type Client_GetTryJob_Call struct {
	*mock.Call
}

// GetTryJob is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Client_Expecter) GetTryJob(ctx interface{}, id interface{}) *Client_GetTryJob_Call {
	return &Client_GetTryJob_Call{Call: _e.mock.On("GetTryJob", ctx, id)}
}

func (_c *Client_GetTryJob_Call) Run(run func(ctx context.Context, id string)) *Client_GetTryJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetTryJob_Call) Return(tryJob continuous_integration.TryJob, err error) *Client_GetTryJob_Call {
	_c.Call.Return(tryJob, err)
	return _c
}

func (_c *Client_GetTryJob_Call) RunAndReturn(run func(ctx context.Context, id string) (continuous_integration.TryJob, error)) *Client_GetTryJob_Call {
	_c.Call.Return(run)
	return _c
}
