---
# Install NVIDIA Graphics Driver; applies only to group "nvidia".
- hosts: nvidia
  tasks:
  - name: Create Temp
    win_file:
      path: c:\Temp
      state: directory
  # This zip was created by opening the self-extracting exe using Archive Manager on Debian and
  # re-zipping the extracted files as a ZIP archive ("Save As").
  - name: Copy the NVIDIA driver ZIP to the host
    win_copy:
      src: "{{ win_package_src }}/NVIDIA Graphics 398.82-desktop-win10-64bit-international-whql.zip"
      dest: c:\Temp\nvidia_gfx.zip
  - name: Extract the NVIDIA driver ZIP
    win_unzip:
      src: c:\Temp\nvidia_gfx.zip
      dest: c:\Temp\NVIDIA
  - name: Install NVIDIA Graphics Driver
    # Command-line args copied from https://lazyadmin.nl/it/deploy-nvidia-drivers/
    win_command: C:\Temp\NVIDIA\setup.exe -noreboot -clean -noeula -nofinish -passive
  - name: Cleanup
    win_file:
      path: c:\Temp\{{ item }}
      state: absent
    loop:
      - NVIDIA
      - nvidia_gfx.zip
