---
# Install NVIDIA Graphics Driver; applies only to group "nvidia".
- hosts: nvidia
  vars:
    # Command-line args copied from https://lazyadmin.nl/it/deploy-nvidia-drivers/
    install_command: C:\Temp\NVIDIA\setup.exe -noreboot -clean -noeula -nofinish -passive
  tasks:
  - name: Create Temp
    win_file:
      path: c:\Temp
      state: directory
  # This zip was created by opening the self-extracting exe using Archive Manager on Debian and
  # re-zipping the extracted files as a ZIP archive ("Save As").
  - name: Copy the NVIDIA driver ZIP to the host
    win_copy:
      src: "{{ win_package_src }}/NVIDIA Graphics 398.82-desktop-win10-64bit-international-whql.zip"
      dest: c:\Temp\nvidia_gfx.zip
  - name: Extract the NVIDIA driver ZIP
    win_unzip:
      src: c:\Temp\nvidia_gfx.zip
      dest: c:\Temp\NVIDIA
  - name: Install NVIDIA Graphics Driver
    win_command: "{{ install_command }}"
    register: setup_result
    ignore_errors: True
  - when: setup_result is failed
    # Sometimes setup.exe returns a non-zero exit code for unknown reason. We reboot and try the
    # command again.
    block:
      - name: Reboot host after NVIDIA Graphics Driver failed
        win_reboot:
      - name: Retry install NVIDIA Graphics Driver
        win_command: "{{ install_command }}"
  - name: Cleanup
    win_file:
      path: c:\Temp\{{ item }}
      state: absent
    loop:
      - NVIDIA
      - nvidia_gfx.zip
