---
# Install NVIDIA Graphics Driver; applies only to group "nvidia".
- hosts: nvidia
  tasks:
  - name: Create Temp
    win_file:
      path: c:\Temp
      state: directory
  # The NVIDIA driver Uses the same product_id for multiple versions, so win_package doesn't work.
  - name: Copy the NVIDIA driver EXE to the host
    win_copy:
      src: "{{ win_package_src }}/NVIDIA Graphics 398.82-desktop-win10-64bit-international-whql.exe"
      dest: c:\Temp\nvidia_gfx.exe
  - name: Install NVIDIA Graphics Driver
    # -s means silently install (discovered by guess-and-check).
    # Note that in previous versions this would only extract the driver; see git history if this
    # behavior reverts.
    win_command: c:\Temp\nvidia_gfx.exe -s
  - name: Cleanup NVIDIA
    win_file:
      path: c:\NVIDIA
      state: absent
  - name: Cleanup EXE
    win_file:
      path: c:\Temp\nvidia_gfx.exe
      state: absent
