---
# Add .gitconfig, _netrc, and .boto files to a Skolo bot.
- hosts: all
  tasks:
  # We use a shotgun approach to ensure .gitconfig, _netrc, and .boto exist anywhere they might be
  # needed.
  - name: Copy gitconfig to root
    win_copy:
      src: "{{ win_package_src }}/.gitconfig"
      dest: c:\
  - name: Copy gitconfig to home
    win_copy:
      src: "{{ win_package_src }}/.gitconfig"
      dest: c:\Users\chrome-bot\
  - name: Copy netrc to root
    win_copy:
      src: "{{ win_package_src }}/_netrc"
      dest: c:\
  - name: Copy netrc to home
    win_copy:
      src: "{{ win_package_src }}/_netrc"
      dest: c:\Users\chrome-bot\
  # .boto doesn't need to contain anything, just needs to be present.
  - name: Create boto in root
    win_file:
      path: c:\.boto
      state: touch
  - name: Create boto in home
    win_file:
      path: c:\Users\chrome-bot\.boto
      state: touch
