- name: restart_prometheus
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: prometheus
    daemon_reload: yes

- name: restart_alert_to_pubsub
  become: yes
  systemd:
    enabled: yes
    state: restarted
    name: alert_to_pubsub
    daemon_reload: yes

- name: validate_prometheus_config
  command: /usr/local/bin/promtool check config /etc/prometheus/prometheus.yml

- name: validate_prometheus_rules
  command: /usr/local/bin/promtool check rules /etc/prometheus/alerts.yml
