// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"golang.org/x/oauth2"
)

// NewOAuthConfig creates a new instance of OAuthConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuthConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuthConfig {
	mock := &OAuthConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OAuthConfig is an autogenerated mock type for the OAuthConfig type
type OAuthConfig struct {
	mock.Mock
}

type OAuthConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuthConfig) EXPECT() *OAuthConfig_Expecter {
	return &OAuthConfig_Expecter{mock: &_m.Mock}
}

// AuthCodeURL provides a mock function for the type OAuthConfig
func (_mock *OAuthConfig) AuthCodeURL(state string, opts ...oauth2.AuthCodeOption) string {
	// oauth2.AuthCodeOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, state)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AuthCodeURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, ...oauth2.AuthCodeOption) string); ok {
		r0 = returnFunc(state, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// OAuthConfig_AuthCodeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthCodeURL'
type OAuthConfig_AuthCodeURL_Call struct {
	*mock.Call
}

// AuthCodeURL is a helper method to define mock.On call
//   - state string
//   - opts ...oauth2.AuthCodeOption
func (_e *OAuthConfig_Expecter) AuthCodeURL(state interface{}, opts ...interface{}) *OAuthConfig_AuthCodeURL_Call {
	return &OAuthConfig_AuthCodeURL_Call{Call: _e.mock.On("AuthCodeURL",
		append([]interface{}{state}, opts...)...)}
}

func (_c *OAuthConfig_AuthCodeURL_Call) Run(run func(state string, opts ...oauth2.AuthCodeOption)) *OAuthConfig_AuthCodeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []oauth2.AuthCodeOption
		variadicArgs := make([]oauth2.AuthCodeOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(oauth2.AuthCodeOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *OAuthConfig_AuthCodeURL_Call) Return(s string) *OAuthConfig_AuthCodeURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *OAuthConfig_AuthCodeURL_Call) RunAndReturn(run func(state string, opts ...oauth2.AuthCodeOption) string) *OAuthConfig_AuthCodeURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function for the type OAuthConfig
func (_mock *OAuthConfig) Exchange(ctx context.Context, code string, opts ...oauth2.AuthCodeOption) (*oauth2.Token, error) {
	// oauth2.AuthCodeOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, code)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *oauth2.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...oauth2.AuthCodeOption) (*oauth2.Token, error)); ok {
		return returnFunc(ctx, code, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...oauth2.AuthCodeOption) *oauth2.Token); ok {
		r0 = returnFunc(ctx, code, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...oauth2.AuthCodeOption) error); ok {
		r1 = returnFunc(ctx, code, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OAuthConfig_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type OAuthConfig_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - opts ...oauth2.AuthCodeOption
func (_e *OAuthConfig_Expecter) Exchange(ctx interface{}, code interface{}, opts ...interface{}) *OAuthConfig_Exchange_Call {
	return &OAuthConfig_Exchange_Call{Call: _e.mock.On("Exchange",
		append([]interface{}{ctx, code}, opts...)...)}
}

func (_c *OAuthConfig_Exchange_Call) Run(run func(ctx context.Context, code string, opts ...oauth2.AuthCodeOption)) *OAuthConfig_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []oauth2.AuthCodeOption
		variadicArgs := make([]oauth2.AuthCodeOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(oauth2.AuthCodeOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *OAuthConfig_Exchange_Call) Return(token *oauth2.Token, err error) *OAuthConfig_Exchange_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *OAuthConfig_Exchange_Call) RunAndReturn(run func(ctx context.Context, code string, opts ...oauth2.AuthCodeOption) (*oauth2.Token, error)) *OAuthConfig_Exchange_Call {
	_c.Call.Return(run)
	return _c
}
