# The username we use when interacting with skolo devices. For example, this is
# chrome-bot for test machines, but can be 'admin' for routers or 'ubnt' for
# switches. It will be overridden by values set in hosts.ini.
skolo_account: 'chrome-bot'

# The port on which each app publishes Prometheus metrics.
prometheus:
  monitoring:
    ports:
      metadata_server_ansible: 20010
      router_backup_ansible: 20011
      powercycle_server_ansible: 20012
      alert_to_pubsub_ansible: 20013
      test_machine_monitor: 20014

# The port that the metadata server is serving on.
metadata_server_port: 9000
