# The username we use when interacting with skolo devices. For example, this is
# chrome-bot for test machines, but can be 'admin' for routers or 'ubnt' for
# switches. It will be overridden by values set in hosts.ini.
skolo_account: 'chrome-bot'
