- hosts: all
  remote_user: chrome-bot
  become_user: root
  become: yes
  become_method: sudo
  tasks:

     - command: systemctl daemon-reload

     - service: name=collectd enabled=yes state=restarted
