name: jsdoc

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main", "workflow" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write    

    steps:
    - name: Checkout goldmine repo.
      uses: actions/checkout@v5
      with:
        path: main

    - name: Generate a token that has write access to the k8s-config repo via an app.
      id: generate-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Checkout k8s config repo.
      uses: actions/checkout@v5
      with:
        repository: goldmine-build/k8s-config
        token: ${{ steps.generate-token.outputs.token }}
        path: k8s-config

    - name: Log in to the GitHub Container registry.
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push jsdoc to the container registry.
      working-directory: ./main
      run: bazelisk run --stamp //jsdoc:jsdoc_push

    - name: Update the image reference in the k8s-config repo.
      working-directory: ./k8s-config/jsdoc
      run: kustomize edit set image "ghcr.io/goldmine-build/jsdoc@*=*@`cat ../../main/_bazel_bin/jsdoc/jsdoc_tag.txt`"

    - name: Commit and push to k8s-config.
      working-directory: ./k8s-config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "[automated] Workflow commit from jsdoc push."
        git push      